// Inhalte der Website – Perfect Shape Zürich
// Alle Texte in Schweizer Hochdeutsch (ss statt ß).

export const SITE = {
  name: 'Perfect Shape Zürich',
  shortName: 'Perfect Shape',
  url: 'https://perfectshape-zuerich.ch',
  phone: '+41 76 608 61 61',
  phoneHref: 'tel:+41766086161',
  whatsapp: 'https://wa.me/41766086161',
  email: 'perfectshapezuerich@gmail.com',
  street: 'Bahnhofstrasse 94',
  floor: '2. Etage',
  zip: '8001',
  city: 'Zürich',
  booking: 'https://book.timify.com/widget/?accountId=5abe4d8a9632650f1b687bb5&locale=de-DE',
  bookingWidget: 'https://book.timify.com/widget/?accountId=5abe4d8a9632650f1b687bb5&locale=de-DE&hideCloseButton=1',
  instagram: 'https://www.instagram.com/perfectshape_zurich/',
  facebook: 'https://www.facebook.com/perfectshapezurich',
  googleMaps: 'https://www.google.com/maps?cid=15609887584479979352',
  route: 'https://www.google.com/maps/dir/?api=1&destination=Perfect+Shape+Bahnhofstrasse+94+8001+Z%C3%BCrich',
  // ▼ Von der Kundin zu ergänzen – leer/null lassen = wird nicht angezeigt
  googleRating: null, // z. B. 4.9 (Durchschnitt laut Google-Profil)
  googleReviewCount: null, // z. B. 87 (Anzahl Google-Bewertungen)
  // Öffnungszeiten, z. B. { days: ['Mo', 'Tu', 'We', 'Th', 'Fr'], de: 'Mo–Fr', en: 'Mon–Fri', opens: '09:00', closes: '19:00' }
  hours: [],
  mapEmbed: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2701.843490410852!2d8.537066977004203!3d47.375973071169746!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47900a069d042a6d%3A0xd8a1760da8b5a758!2sPerfect%20Shape!5e0!3m2!1sde!2sch!4v1758100930328!5m2!1sde!2sch',
};

export const CATEGORIES = [
  { id: 'aesthetik', name: 'Ästhetische Medizin', short: 'Injektionen, Fäden & Regeneration', image: 'aesthetische-medizin-zuerich' },
  { id: 'laser', name: 'Laserbehandlungen', short: 'Haarentfernung & Laser-Straffung', image: 'laserbehandlungen-zuerich' },
  { id: 'apparativ', name: 'Apparative Kosmetik', short: 'Hautbild, Poren & Kollagen', image: 'apparative-kosmetik-behandlung-zuerich' },
  { id: 'massage', name: 'Massagen', short: 'Entspannung & Körperkontur', image: 'massagen-zuerich' },
  { id: 'peeling', name: 'Fruchtsäure & Peeling', short: 'Glow & ebenmässiger Teint', image: 'fruchtsaeure-peeling-behandlung-zuerich' },
];

const STD_CONTRA_NOTE = 'Die finale Eignung wird ärztlich beurteilt.';

export const TREATMENTS = [
  {
    slug: 'fadenlifting-zuerich',
    oldSlug: 'pdofaden',
    category: 'aesthetik',
    name: 'PDO Fäden',
    navName: 'Fadenlifting (PDO Fäden)',
    keyword: 'Fadenlifting Zürich',
    title: 'Fadenlifting Zürich – PDO Fäden ohne OP | Perfect Shape',
    description: 'Fadenlifting mit PDO-Fäden in Zürich: natürliches Lifting ohne Skalpell, Ergebnis bis 18–24 Monate. V-Lifting, Jawline & Doppelkinn. Jetzt Termin buchen.',
    h1: 'Fadenlifting',
    h1Accent: 'mit PDO Fäden',
    lead: 'Natürliches Lifting ohne Skalpell: Resorbierbare PDO-/PLLA-Fäden liften sofort und regen den Kollagenaufbau an – für langanhaltende Festigkeit. Minimalinvasiv, ambulant, natürlich.',
    card: 'Natürliches Lifting ohne Skalpell – für Wangen, Jawline & Hals.',
    image: 'fadenlifting-zuerich',
    imageAlt: 'Fadenlifting mit PDO Fäden in Zürich – Vektoren für ein natürliches Gesichtslifting',
    chips: ['45–75 Min.', 'Ø 18–24 Monate', 'Downtime 1–3 Tage'],
    intro: 'Das Fadenlifting – auch PDO-Fadenlifting oder Thread Lift genannt – ist eine der gefragtesten minimalinvasiven Methoden, um erschlaffte Gesichtskonturen ohne Operation zu straffen. Bei Perfect Shape an der Bahnhofstrasse in Zürich planen wir jede Behandlung individuell nach Ihrer Anatomie: vom sanften V-Lifting über die Definition der Jawline bis zur Reduktion des Doppelkinns.',
    what: {
      title: 'Was ist Fadenlifting?',
      text: 'Über Mikrozugänge werden resorbierbare PDO-/PLLA-Fäden eingelegt. Feine Mikrowiderhäkchen repositionieren das Gewebe sanft; der natürliche Abbau der Fäden fördert die Neokollagenese. So verbinden sich ein sofort sichtbarer Lifting-Effekt und eine strukturelle Hautverbesserung.',
      bullets: ['Natürliches Lifting ohne Schnitt und Narben', 'Definition von Wangen, Jawline und Hals', 'Kurz, ambulant, geringe Ausfallzeit'],
    },
    indications: { title: 'Indikationen', items: ['Hängebäckchen („Jowls“)', 'Verlust der Wangenfülle', 'Konturierung der Jawline', 'Leichte Halserschlaffung', 'Doppelkinn & Tränensäcke'] },
    contra: { title: 'Kontraindikationen', items: ['Akute Hautinfektionen', 'Schwangerschaft/Stillzeit', 'Gerinnungsstörungen', 'Unrealistische Erwartungen'], note: STD_CONTRA_NOTE },
    steps: [
      ['Beratung & Planung', 'Analyse, Vektorplanung und ausführliche Aufklärung.'],
      ['Lokale Betäubung', 'Komfortabler Ablauf mit Betäubungscreme oder Infiltration.'],
      ['Fäden einlegen', 'Schonend über Mikrozugänge entlang definierter Vektoren.'],
      ['Feintuning & Nachsorge', 'Symmetrie-Check, sterile Abdeckung, klare Empfehlungen.'],
    ],
    results: {
      title: 'Ergebnisse & Haltbarkeit',
      items: ['Lift sofort sichtbar, finale Form nach 2–4 Wochen', 'Kollagenaufbau verbessert die Elastizität über Monate', 'Durchschnittlich 18–24 Monate Haltbarkeit'],
      note: '*Ergebnisse variieren individuell.',
      stats: [['45–75', 'Minuten'], ['18–24', 'Monate Haltbarkeit'], ['1–3', 'Tage Downtime']],
    },
    prices: [
      { name: 'Perfectshape V-Fadenlifting', detail: 'Ganzes Gesicht inkl. Jawline – 6 Stück pro Seite', desc: 'Ganzheitliches Lifting für Gesicht und Kieferlinie ohne Operation – mit langanhaltendem Ergebnis bis zu 18 Monaten.', price: 1700, featured: true },
      { name: 'Spannkraft mit Kollagen-Fäden', detail: '40 Stück', desc: 'Kollagenbildende Fäden stärken die Hautstruktur und verbessern sichtbar die Elastizität innerhalb weniger Wochen.', price: 550 },
      { name: 'Doppelkinn-Reduktion', detail: 'Kombi-Behandlung Fäden & Lipolyse', desc: 'Kombination aus Fäden und Lipolyse zur effektiven Reduktion des Doppelkinns und Definition der Kieferlinie.', price: 270 },
      { name: 'Tränensäcke-Reduktion mit Fäden', detail: '5 Stück pro Seite', desc: 'Straffung und Glättung der Augenpartie für ein frischeres, wacheres Aussehen.', price: 250 },
      { name: 'Nasolabialfalte mit Multifäden', desc: 'Sanfte Straffung der Nasolabialfalten durch spezielle Multifäden für ein glatteres Hautbild.', price: 240 },
      { name: 'Fadenlifting Körper', detail: 'Bauch, Trizeps, Busen', desc: 'Fadenlifting für Körperzonen – individuell abgestimmt je nach Behandlungsbereich.', price: null, priceText: 'auf Anfrage' },
    ],
    faq: [
      ['Wie lange hält das Ergebnis eines Fadenliftings?', 'In der Regel hält der Lifting-Effekt zwischen 18 und 24 Monaten. Während sich die Fäden nach einigen Monaten selbst auflösen, bleibt der Effekt dank der Kollagenneubildung deutlich länger sichtbar.'],
      ['Ist das Fadenlifting schmerzhaft?', 'Die Behandlung erfolgt unter lokaler Betäubung (Creme oder Infiltration), sodass Sie meist nur ein leichtes Druckgefühl spüren. Viele Patientinnen und Patienten empfinden den Eingriff als sehr gut tolerierbar.'],
      ['Wie lange ist die Ausfallzeit nach dem Eingriff?', 'Die Downtime beträgt meist nur 1–3 Tage. Leichte Schwellungen oder blaue Flecken können auftreten und klingen in der Regel rasch ab.'],
      ['Was kostet ein Fadenlifting in Zürich?', 'Bei Perfect Shape beginnt die Behandlung der Nasolabialfalte mit Multifäden ab CHF 240. Das komplette Perfectshape V-Fadenlifting (ganzes Gesicht inkl. Jawline) kostet CHF 1700. Den finalen Preis legen wir nach der persönlichen Beratung fest.'],
    ],
    related: ['biostimulatoren-zuerich', 'hyaluron-zuerich', 'endolift-zuerich'],
  },
  {
    slug: 'hyaluron-zuerich',
    oldSlug: 'hyaluronsaure',
    category: 'aesthetik',
    name: 'Hyaluronsäure',
    navName: 'Hyaluronsäure & Lippen',
    keyword: 'Hyaluron Zürich',
    title: 'Hyaluron Zürich – Lippen & Filler ab CHF 160 | Perfect Shape',
    description: 'Hyaluron in Zürich: natürlicher Lippenaufbau ab CHF 160, Nasenkorrektur, Kinn & Augenringe – ehrlich beraten, ohne Overfilling. Jetzt Termin buchen.',
    h1: 'Hyaluronsäure',
    h1Accent: 'Volumen, Kontur & Glow',
    lead: 'Präzise platzierte Hyaluron-Filler für natürliche Konturen, gezielten Volumenaufbau und langanhaltende Hydration. Schonend, individuell geplant, mit sofort sichtbarem Ergebnis.',
    card: 'Lippen, Kinn, Nase & Augenringe – natürlich, ohne Overfilling.',
    image: 'hyaluron-zuerich',
    imageAlt: 'Lippenaufbau mit Hyaluronsäure in Zürich – natürliche Lippen',
    chips: ['30–45 Min.', 'Ø 6–12 Monate', 'Kaum Downtime'],
    intro: 'Ob sanfter Lippenaufbau, eine definierte Kinnlinie oder frischere Augenpartie: Hyaluronsäure-Filler gehören zu den vielseitigsten Behandlungen der ästhetischen Medizin. In unserem Studio in Zürich setzen wir auf hochwertige Markenprodukte und eine ehrliche Beratung – wir empfehlen nur, was wirklich zu Ihrem Gesicht passt.',
    what: {
      title: 'Was ist Hyaluronsäure?',
      text: 'Hyaluronsäure ist ein natürlich vorkommendes Molekül, das Wasser bindet und der Haut Volumen sowie Elastizität verleiht. Moderne HA-Filler werden je nach Region und Ziel (z. B. Lippen, Wangen, Jawline, Nasolabialfalte) gezielt in unterschiedliche Hautschichten eingebracht – für harmonische, natürliche Ergebnisse ohne „Overfilling“.',
      bullets: ['Sofort sichtbare, natürlich wirkende Resultate', 'Präzise Konturierung von Lippen, Wangen, Jawline und Kinn', 'Feuchtigkeits-Boost und verbesserte Hautqualität'],
    },
    indications: { title: 'Indikationen', items: ['Volumenaufbau (Wangen, Kinn, Schläfen)', 'Lippenform, Lippenvolumen & Lippenrand', 'Falten: Nasolabial- und Marionettenfalten', 'Augenringe & Tränenrinne', 'Feuchtigkeitsaufbau (Skinbooster)'] },
    contra: { title: 'Kontraindikationen', items: ['Akute Entzündungen/Infektionen im Behandlungsareal', 'Schwangerschaft/Stillzeit', 'Bekannte Filler-Unverträglichkeit', 'Unrealistische Erwartungen'], note: STD_CONTRA_NOTE },
    steps: [
      ['Beratung & Analyse', 'Gesichtsproportionen, Hautqualität, Produktwahl & Dosierung.'],
      ['Betäubung & Vorbereitung', 'Creme oder Leitungsanästhesie je nach Region, gründliche Desinfektion.'],
      ['Injektion & Formgebung', 'Gewebeschonende Technik (Nadel/Kanüle), sanftes Ausmodellieren.'],
      ['Kontrolle & Nachsorge', 'Symmetrie-Check, Kühlung, kurze Verhaltensempfehlungen.'],
    ],
    results: {
      title: 'Ergebnisse & Haltbarkeit',
      items: ['Ergebnis sofort sichtbar, Feinanpassung in den ersten Tagen', 'Haltbarkeit je nach Region/Produkt: ca. 6–12 Monate', 'Sehr geringe Ausfallzeit, gelegentlich leichte Schwellung'],
      note: '*Abhängig von Region, Haut, Produkt und Lebensstil.',
      stats: [['30–45', 'Minuten'], ['0–1', 'Tage Downtime'], ['6–12', 'Monate Haltbarkeit']],
    },
    prices: [
      { name: 'Lippenaufbau', desc: 'Präzises Lippenmodellieren mit Hyaluronsäure für mehr Volumen und natürliche Konturen.', price: 160, priceText: 'CHF 160 (0.5 ml) · CHF 270 (1.0 ml)', featured: true },
      { name: 'Nasenkorrektur', desc: 'Nicht-chirurgische Nasenkorrektur mit Fillern – schnelle Ergebnisse ohne Ausfallzeit.', price: 380 },
      { name: 'Kinnaufbau / Nasolabialfalte / Marionettenfalten', detail: '1.0 ml', desc: 'Auffüllen und Modellieren von Gesichtskonturen für ein harmonisches und jugendliches Aussehen.', price: 300 },
      { name: 'Augenringe-Unterspritzung', desc: 'Sanftes Unterspritzen der Tränenrinne zur Reduktion dunkler Augenringe und für ein frisches Aussehen.', price: 350 },
      { name: 'Faltenbehandlung mimischer Falten', desc: 'Behandlung mimischer Falten (Stirn, Zornesfalte, Krähenfüsse) mit Botulinumtoxin bei natürlicher Mimik.', price: 250, from: true },
    ],
    faq: [
      ['Wie lange hält eine Behandlung mit Hyaluronsäure?', 'Je nach Region, Produkt und Stoffwechsel etwa 6–12 Monate. In Bereichen mit viel Bewegung (z. B. Lippen) meist kürzer als in statischeren Regionen.'],
      ['Ist die Behandlung schmerzhaft?', 'Wir arbeiten mit Betäubungscreme und/oder lokaler Anästhesie. Die meisten Patientinnen und Patienten empfinden die Injektion als gut tolerierbar; ein kurzes Druck- oder Spannungsgefühl ist möglich.'],
      ['Welche Nebenwirkungen gibt es und was gilt für die Nachsorge?', 'Kurzzeitig sind Schwellungen oder Blutergüsse möglich. 24 Stunden starke Hitze (Sauna/Solarium) und intensiven Sport vermeiden, das Areal ggf. kühlen. Bei Fragen sind wir jederzeit für Sie da.'],
      ['Was kostet ein Lippenaufbau in Zürich?', 'Ein Lippenaufbau mit Hyaluronsäure kostet bei Perfect Shape CHF 160 für 0.5 ml und CHF 270 für 1.0 ml. Wie viel sinnvoll ist, besprechen wir ehrlich in der Beratung.'],
    ],
    related: ['biostimulatoren-zuerich', 'fadenlifting-zuerich', 'mesotherapie-zuerich'],
  },
  {
    slug: 'mesotherapie-zuerich',
    oldSlug: 'mesotherapie',
    category: 'aesthetik',
    name: 'Mesotherapie',
    navName: 'Mesotherapie',
    keyword: 'Mesotherapie Zürich',
    title: 'Mesotherapie Zürich – Glow, Haare & Augen | Perfect Shape',
    description: 'Mesotherapie in Zürich für Glow, Haarwachstum, Augenringe & Cellulite. Individuelle Wirkstoff-Cocktails ab CHF 130 – jetzt Termin buchen.',
    h1: 'Mesotherapie',
    h1Accent: 'Haut-Boost für Glow & Vitalität',
    lead: 'Schonende Mikroinjektionen aus massgeschneiderten Wirkstoff-Cocktails (Vitamine, Aminosäuren, Hyaluron) fördern Durchblutung, Regeneration und Feuchtigkeit – für sichtbar frischere, feinere Haut.',
    card: 'Massgeschneiderte Wirkstoff-Cocktails für Haut, Haare & Augenpartie.',
    image: 'mesotherapie-zuerich',
    imageAlt: 'Mesotherapie im Gesicht in Zürich – Mikroinjektionen für frische Haut',
    chips: ['30–45 Min.', 'Kur: 3–6 Sitzungen', 'Abstand 2–4 Wochen'],
    intro: 'Mesotherapie ist der Klassiker für alle, die ihrer Haut einen intensiven Frische-Kick geben möchten – oder gezielt Haarausfall, Augenringe und Cellulite behandeln wollen. Bei Perfect Shape in Zürich stellen wir den Wirkstoff-Cocktail individuell für Ihr Ziel zusammen.',
    what: {
      title: 'Was ist Mesotherapie?',
      text: 'Die Mesotherapie kombiniert sehr feine Mikroinjektionen mit individuell abgestimmten Wirkstoff-Mixturen. So gelangen Vitamine, Antioxidantien, Peptide und unvernetzte Hyaluronsäure genau dorthin, wo sie wirken sollen – in die oberflächlichen Hautschichten.',
      bullets: ['Verbesserte Hydration & Hautqualität („Glow“)', 'Feinere Poren, ebenmässigeres Hautbild', 'Stimulation von Stoffwechsel & Regeneration'],
    },
    indications: { title: 'Indikationen', items: ['Müdigkeits- & Trockenheitsfältchen', 'Fahler Teint, „Glow“-Verlust', 'Feine Poren-/Strukturverbesserung', 'Hals, Dekolleté, Hände', 'Haarausfall & dünnes Haar'] },
    contra: { title: 'Kontraindikationen', items: ['Akute Entzündungen/Infektionen im Areal', 'Schwangerschaft/Stillzeit', 'Bekannte Unverträglichkeit gegen Inhaltsstoffe', 'Gerinnungsstörungen'], note: STD_CONTRA_NOTE },
    steps: [
      ['Beratung & Rezeptur', 'Analyse von Hautzustand & Zielen, Auswahl des Wirkstoff-Cocktails.'],
      ['Vorbereitung', 'Reinigung, ggf. Betäubungscreme, sorgfältige Desinfektion.'],
      ['Mikroinjektionen', 'Feinste Depots in die obere Dermis (manuell oder mit Mesopistole).'],
      ['Abschluss & Pflege', 'Kühlung, Pflegeempfehlungen, Planung der Kur.'],
    ],
    results: {
      title: 'Ergebnisse & Haltbarkeit',
      items: ['Frischer, prallerer Teint oft schon nach der ersten Sitzung', 'Deutliche Strukturverbesserung nach einer Kur (3–6 Sitzungen)', 'Erhalt durch Auffrischung alle 3–6 Monate'],
      note: '*Je nach Haut, Region und Pflege-Routine.',
      stats: [['30–45', 'Minuten'], ['3–6', 'Sitzungen (Kur)'], ['3–6', 'Monate Erhalt']],
    },
    prices: [
      { name: 'Mesotherapie Haarfollikel-Therapie', desc: 'Stimuliert die Haarfollikel, stärkt die Haarstruktur und fördert das natürliche Haarwachstum.', price: 200, extra: '4× Kur – CHF 700', featured: true },
      { name: '„Like a BTX“ Mesotherapie', desc: 'Glättender Effekt ohne Botulinumtoxin – für ein strafferes und feineres Hautbild.', price: 250 },
      { name: '„Cellu Killer“ Mesotherapie', desc: 'Spezielle Behandlung zur Reduktion von Cellulite und Verbesserung der Hautstraffheit an Problemzonen.', price: 200 },
      { name: 'Augenringe-Mesotherapie', desc: 'Feuchtigkeitsspendende und aufhellende Behandlung der empfindlichen Augenpartie.', price: 130 },
    ],
    faq: [
      ['Wie viele Sitzungen sind sinnvoll?', 'Für sichtbare und stabile Ergebnisse empfehlen wir eine Kur von 3–6 Sitzungen im Abstand von 2–4 Wochen. Auffrischungen alle 3–6 Monate erhalten den Effekt.'],
      ['Tut die Mesotherapie weh?', 'Mit Betäubungscreme und sehr feinen Nadeln wird die Behandlung in der Regel gut toleriert. Kurzzeitiges Brennen oder Piksen ist möglich und klingt rasch ab.'],
      ['Gibt es Nebenwirkungen?', 'Vorübergehende Rötung, kleine Papeln oder punktförmige Hämatome sind möglich und verschwinden meist innerhalb weniger Tage. Bitte 24 Stunden Sauna/Solarium und intensiven Sport vermeiden.'],
      ['Hilft Mesotherapie bei Haarausfall?', 'Ja, die Haarfollikel-Therapie stimuliert die Kopfhaut gezielt und kann das natürliche Haarwachstum fördern. Wir empfehlen eine Kur von 4 Sitzungen (CHF 700).'],
    ],
    related: ['prp-vampirelifting-zuerich', 'hyaluron-zuerich', 'microdermabrasion-zuerich'],
  },
  {
    slug: 'biostimulatoren-zuerich',
    oldSlug: 'biostimulatoren',
    category: 'aesthetik',
    name: 'Biostimulatoren',
    navName: 'Biostimulatoren',
    keyword: 'Biostimulatoren Zürich',
    title: 'Biostimulatoren Zürich – Kollagenaufbau | Perfect Shape',
    description: 'Biostimulatoren in Zürich: Polynukleotide & PLLA Liquid Facelift für natürlichen Kollagenaufbau, 12–24 Monate Wirkung. Ab CHF 350 – jetzt buchen.',
    h1: 'Biostimulatoren',
    h1Accent: 'Kollagenaufbau von innen',
    lead: 'Biostimulatoren aktivieren die körpereigene Kollagenneubildung – für straffere Konturen, bessere Hautqualität und sehr natürliche, schrittweise zunehmende Ergebnisse mit langer Haltbarkeit.',
    card: 'Polynukleotide & PLLA – natürliche Straffung durch eigenes Kollagen.',
    image: 'biostimulatoren-zuerich',
    imageAlt: 'Behandlung mit Biostimulatoren in Zürich – Kollagenaufbau im Gesicht',
    chips: ['30–50 Min.', 'Aufbau 6–12 Wochen', 'Haltbarkeit 12–24 Monate'],
    intro: 'Biostimulatoren wie Polynukleotide oder Poly-L-Milchsäure (PLLA) sind die moderne Antwort auf nachlassende Spannkraft: Statt Volumen „aufzufüllen“, regen sie Ihre Haut an, selbst wieder Kollagen zu bilden. Das Ergebnis entwickelt sich sanft über Wochen – und wirkt dadurch besonders natürlich.',
    what: {
      title: 'Was sind Biostimulatoren?',
      text: 'Biostimulatoren (z. B. Poly-L-Milchsäure, Polynukleotide) regen gezielt die Kollagenneubildung in der Haut an. Im Unterschied zu klassischen Fillern, die Volumen primär durch das injizierte Material liefern, entsteht der Effekt hier durch die eigene Gewebereaktion – dichteres, elastischeres Gewebe und eine natürlich wirkende Straffung.',
      bullets: ['Sehr natürliche, stufenweise Zunahme des Effekts', 'Verbesserte Dichte, Elastizität & Hautstruktur', 'Langanhaltend durch körpereigenen Kollagenaufbau'],
    },
    indications: { title: 'Indikationen', items: ['Leichter bis moderater Volumen- & Strukturverlust', 'Wangen, Jawline/Kinnlinie, Kinn, Schläfen', 'Hauterschlaffung, Kontur-Definition', 'Hautqualität: Porenfeinheit & Elastizität'] },
    contra: { title: 'Kontraindikationen', items: ['Akute Entzündungen/Infektionen im Areal', 'Schwangerschaft/Stillzeit', 'Aktive Autoimmunerkrankungen, Keloidneigung', 'Unverträglichkeiten gegenüber Inhaltsstoffen'], note: STD_CONTRA_NOTE },
    steps: [
      ['Beratung & Planung', 'Analyse von Anatomie & Hautqualität, Auswahl des geeigneten Biostimulators.'],
      ['Vorbereitung', 'Reinigung, ggf. Betäubungscreme, sterile Desinfektion.'],
      ['Injektion', 'Schonende Technik (Nadel/Kanüle) für einen gleichmässigen Aufbau.'],
      ['Aufbauphase & Kontrolle', 'Der Effekt entwickelt sich über Wochen; Kontrolle nach 8–12 Wochen.'],
    ],
    results: {
      title: 'Ergebnisse & Haltbarkeit',
      items: ['Erste Veränderungen nach einigen Wochen, Peak nach 2–3 Monaten', 'Typische Haltbarkeit 12–24 Monate (produkt- & arealabhängig)', 'Sehr natürliches Remodelling – keine „Überfüllung“'],
      note: '*Abhängig von Areal, Produkt, Lebensstil und individueller Gewebereaktion.',
      stats: [['30–50', 'Minuten'], ['6–12', 'Wochen Aufbau'], ['12–24', 'Monate Haltbarkeit']],
    },
    prices: [
      { name: 'Liquid Facelift mit PLLA-Biostimulatoren', detail: '10 ml', desc: 'Umfassende Gesichtsverjüngung durch Biostimulatoren – ganz ohne Skalpell.', price: 650, featured: true },
      { name: 'Haut-Revitalisierung mit Polynukleotiden', desc: 'Minimalinvasive Injektionstherapie mit Polynukleotiden (DNA-Fragmenten), die die natürliche Zellregeneration ankurbelt und die Kollagenbildung fördert.', price: 350 },
    ],
    faq: [
      ['Worin unterscheiden sich Biostimulatoren von Fillern?', 'Filler geben Volumen primär durch das Material selbst. Biostimulatoren regen die eigene Kollagenbildung an – der Effekt wächst über Wochen, wirkt sehr natürlich und hält in der Regel länger.'],
      ['Wie viele Sitzungen brauche ich?', 'Je nach Ausgangslage sind 1–3 Sitzungen üblich. Nach 8–12 Wochen kontrollieren wir den Aufbau und ergänzen bei Bedarf.'],
      ['Gibt es Ausfallzeiten?', 'Meist gering. Kurzzeitig sind Rötung, Schwellung oder kleine Hämatome möglich. 24 Stunden starke Hitze und intensiven Sport vermeiden.'],
    ],
    related: ['fadenlifting-zuerich', 'prp-vampirelifting-zuerich', 'rf-needling-zuerich'],
  },
  {
    slug: 'prp-vampirelifting-zuerich',
    oldSlug: 'prp-vampirelifting',
    category: 'aesthetik',
    name: 'PRP-Vampirelifting',
    navName: 'PRP-Vampirelifting',
    keyword: 'PRP Vampirelifting Zürich',
    title: 'PRP Vampirelifting Zürich – Eigenblut | Perfect Shape',
    description: 'PRP-Vampirelifting in Zürich: Eigenplasma für Glow, feinere Haut & gegen Haarausfall. 100 % körpereigen. Ab CHF 300 – jetzt Termin buchen.',
    h1: 'PRP-Vampirelifting',
    h1Accent: 'Regeneration mit Eigenplasma',
    lead: 'Konzentriertes, aus Ihrem Blut gewonnenes plättchenreiches Plasma (PRP) stimuliert die körpereigene Regeneration: mehr Glow, feinere Struktur, elastischere Haut – ganz natürlich und ohne Fremdmaterial.',
    card: 'Eigenplasma für Glow, Elastizität & kräftigeres Haar.',
    image: 'prp-vampirelifting-zuerich',
    imageAlt: 'PRP-Vampirelifting in Zürich – Eigenblutbehandlung für Gesicht und Kopfhaut',
    chips: ['45–60 Min.', 'Kur: 3 Sitzungen', 'Abstand 4–6 Wochen'],
    intro: 'Beim PRP-Vampirelifting nutzen wir die Regenerationskraft Ihres eigenen Körpers. Die Eigenblutbehandlung ist ideal für alle, die eine natürliche Hautverjüngung ohne Filler wünschen – und eine bewährte Option bei Haarausfall.',
    what: {
      title: 'Was ist PRP-Vampirelifting?',
      text: 'Beim PRP-Vampirelifting wird aus einer kleinen Blutprobe Ihr Eigenplasma gewonnen, das reich an Wachstumsfaktoren ist. Dieses PRP wird in die Zielareale injiziert oder mit Microneedling eingearbeitet. Das Ergebnis: Anregung von Zellregeneration, Kollagenneubildung und verbesserter Hautdichte – 100 % natürlich.',
      bullets: ['Natürliche Biostimulation ohne Fremdmaterial', 'Mehr Glow, Elastizität und weniger feine Fältchen', 'Auch für Hals, Dekolleté, Hände oder Kopfhaut'],
    },
    indications: { title: 'Indikationen', items: ['Müder Teint, nachlassende Elastizität', 'Feinste Fältchen (z. B. Augen-/Lippenumfeld)', 'Struktur & Porenbild, feine Narben', 'Haarausfall, dünner werdendes Haar'] },
    contra: { title: 'Kontraindikationen', items: ['Akute Infektionen/Entzündungen im Areal', 'Gerinnungsstörungen, Antikoagulation', 'Schwangerschaft/Stillzeit', 'Schwere Autoimmunerkrankungen'], note: STD_CONTRA_NOTE },
    steps: [
      ['Blutabnahme & Aufbereitung', 'Schonende Entnahme, Zentrifugation zur Gewinnung des PRP.'],
      ['Optionale Betäubung', 'Betäubungscreme je nach Region, gründliche Desinfektion.'],
      ['Applikation', 'Injektionen punktuell/flächig oder Einarbeitung via Microneedling.'],
      ['Nachsorge & Kurplanung', 'Kühlung, Pflege, Lichtschutz; Planung der Serie.'],
    ],
    results: {
      title: 'Ergebnisse & Haltbarkeit',
      items: ['Erste Veränderungen nach 2–4 Wochen, Peak nach 2–3 Monaten', 'Typische Haltbarkeit 9–18 Monate', 'Sehr natürliches Remodelling durch körpereigene Faktoren'],
      note: '*Variiert je nach Region, Hautzustand, Lebensstil und Kurumfang.',
      stats: [['45–60', 'Minuten'], ['3', 'Sitzungen (Kur)'], ['9–18', 'Monate Haltbarkeit']],
    },
    prices: [
      { name: 'PRP – Gesicht', desc: 'Eigenblutbehandlung zur Hautverjüngung und natürlichen Regeneration.', price: 400, featured: true },
      { name: 'PRP – Kopfhaut', desc: 'Stärkt die Haarwurzeln, reduziert Haarausfall und fördert das Haarwachstum.', price: 300 },
    ],
    faq: [
      ['Wie viele Sitzungen brauche ich?', 'Für stabile Effekte empfehlen wir eine Kur aus 3 Sitzungen im Abstand von 4–6 Wochen. Eine Auffrischung 1–2× pro Jahr hilft, das Ergebnis zu erhalten.'],
      ['Gibt es Ausfallzeit?', 'Meist nur leichte Rötung oder Schwellung für 1–2 Tage. Bitte 24 Stunden starke Hitze und intensiven Sport vermeiden und auf Sonnenschutz achten.'],
      ['Ist PRP sicher?', 'PRP ist autolog (körpereigen) – das Risiko allergischer Reaktionen ist sehr gering. Kontraindikationen klären wir im Vorgespräch.'],
    ],
    related: ['mesotherapie-zuerich', 'biostimulatoren-zuerich', 'rf-needling-zuerich'],
  },
  {
    slug: 'laser-haarentfernung-zuerich',
    oldSlug: 'permamente haarentfernung',
    category: 'laser',
    name: 'Permanente Haarentfernung',
    navName: 'Laser-Haarentfernung',
    keyword: 'Laser Haarentfernung Zürich',
    title: 'Laser-Haarentfernung Zürich ab CHF 40 | Perfect Shape',
    description: 'Dauerhafte Laser-Haarentfernung (Diodenlaser/SHR) in Zürich: Oberlippe CHF 40, Achseln CHF 80, Full Body CHF 400. Zertifiziert & sicher – jetzt buchen.',
    h1: 'Laser-Haarentfernung',
    h1Accent: 'dauerhaft glatte Haut',
    lead: 'Effiziente, hautschonende Reduktion unerwünschter Haare mit professioneller Laser-/SHR-Technologie. Für nachhaltig glatte Haut an Gesicht, Achseln, Bikinizone, Beinen und weiteren Zonen.',
    card: 'Diodenlaser/SHR für dauerhaft glatte Haut – Gesicht bis Full Body.',
    image: 'laser-haarentfernung-zuerich',
    imageAlt: 'Permanente Laser-Haarentfernung an den Beinen in Zürich',
    chips: ['15–60 Min.', '6–8 Sitzungen', 'Diodenlaser/SHR'],
    intro: 'Nie wieder rasieren, wachsen oder zupfen: Mit der permanenten Haarentfernung per Diodenlaser bzw. SHR-Technologie reduzieren wir unerwünschten Haarwuchs nachhaltig – sanft, sicher und mit transparenten Preisen pro Zone. Unsere Behandlungen führt eine zertifizierte Laserschutzbeauftragte durch.',
    what: {
      title: 'Wie funktioniert die permanente Haarentfernung?',
      text: 'Mithilfe von Laser-/SHR-Impulsen wird die Haarwurzel (Follikel) gezielt erwärmt und inaktiviert. Da Haare in Zyklen wachsen, werden in mehreren Sitzungen die Follikel in der jeweiligen Wachstumsphase erfasst. Das Resultat: deutlich weniger Haarwuchs bis hin zu langfristig glatter Haut.',
      bullets: ['Sicher & präzise – zielgenau auf die Follikel', 'Hautschonend dank kontrollierter Energieabgabe', 'Nachhaltige Reduktion des Haarwuchses'],
    },
    indications: { title: 'Geeignete Zonen', items: ['Gesicht (Oberlippe, Kinn)', 'Achseln, Arme', 'Bikinizone/Intimbereich', 'Beine, Rücken, Brust, Bauch'] },
    contra: { title: 'Ihre Vorteile', items: ['Zeitsparend: kein Rasieren/Wachsen mehr', 'Weniger eingewachsene Haare & Reizungen', 'Gleichmässige, glatte Haut'], note: 'Die Wirksamkeit ist abhängig von Haarfarbe, Haardichte, Hauttyp und Hormonlage.', positive: true },
    steps: [
      ['Beratung & Test', 'Analyse von Haut/Haar, Aufklärung und ggf. Testimpuls zur Parameterfindung.'],
      ['Vorbereitung', 'Rasierte Zielareale, saubere und trockene Haut; Schutzbrillen.'],
      ['Laserbehandlung', 'Gezielte Impulse über das Areal; Kühlung für mehr Komfort.'],
      ['Nachsorge', 'Kühlen, milde Pflege, UV-Schutz; nächste Sitzung nach 4–8 Wochen.'],
    ],
    results: {
      title: 'Ergebnisse & Haltbarkeit',
      items: ['Haarreduktion sichtbar bereits nach wenigen Sitzungen', 'Dauerhafte Wirkung nach einer Serie von 6–8 Sitzungen', 'Erhaltungssitzung 1–2× pro Jahr kann sinnvoll sein'],
      note: '*Individuell je nach Haarfarbe/-stärke, Hauttyp, Areal und Hormonsituation.',
      stats: [['15–60', 'Minuten / Sitzung'], ['6–8', 'Sitzungen (Serie)'], ['4–8', 'Wochen Abstand']],
    },
    prices: [
      { name: 'Oberlippe / Kinn', desc: 'Effektive Haarentfernung kleiner Gesichtsbereiche für langanhaltende Glätte.', price: 40 },
      { name: 'Achseln / Bikinilinie', desc: 'Sanfte und gründliche Laserenthaarung für dauerhafte Ergebnisse.', price: 80, featured: true },
      { name: 'Bikini Front', desc: 'Präzise Haarentfernung im vorderen Bikinibereich.', price: 100 },
      { name: 'Full Bikini + Pofalte', desc: 'Umfassende Haarentfernung im Intimbereich für glatte Haut ohne Rasur.', price: 120 },
      { name: 'Unterschenkel / Arme', desc: 'Dauerhafte Haarfreiheit an Beinen oder Armen.', price: 120 },
      { name: 'Rücken / Brust & Bauch', desc: 'Effiziente Behandlung grosser Flächen für eine glatte Hautstruktur.', price: 140 },
      { name: 'Ganze Beine', desc: 'Komplettbehandlung beider Beine für ein dauerhaft glattes Ergebnis.', price: 200 },
      { name: 'Full Body', desc: 'Ganzkörper-Laserbehandlung für rundum haarfreie Haut.', price: 400 },
    ],
    priceNote: 'Fragen Sie nach unseren Sparpaketen für optimale Ergebnisse zu einem attraktiven Preis.',
    faq: [
      ['Wie viele Sitzungen brauche ich?', 'In der Regel 6–8 Sitzungen im Abstand von 4–8 Wochen; je nach Areal, Haut/Haar und Zielsetzung kann es variieren.'],
      ['Tut Laser-Haarentfernung weh?', 'Meist wird die Behandlung als gut tolerierbar beschrieben. Die Kühlung reduziert das Wärme- oder Piksgefühl deutlich.'],
      ['Was muss ich vor und nach der Behandlung beachten?', '24–48 Stunden starke Hitze (Sauna/Solarium) und intensiven Sport vermeiden, Sonnenschutz beachten. Zwischen den Sitzungen bitte nur rasieren – nicht wachsen oder zupfen.'],
      ['Für wen ist die Methode geeignet?', 'Viele Hauttypen profitieren. Sehr helle, feine oder graue Haare sprechen weniger an. Im Beratungsgespräch prüfen wir die Eignung und passen die Parameter individuell an.'],
      ['Was kostet Laser-Haarentfernung in Zürich?', 'Bei Perfect Shape kostet eine Sitzung ab CHF 40 (Oberlippe/Kinn), Achseln CHF 80, ganze Beine CHF 200 und Full Body CHF 400.'],
    ],
    related: ['endolift-zuerich', 'carbon-laser-peeling-zuerich', 'rf-needling-zuerich'],
  },
  {
    slug: 'endolift-zuerich',
    oldSlug: 'endolift',
    category: 'laser',
    name: 'Endolift®',
    navName: 'Endolift®',
    keyword: 'Endolift Zürich',
    title: 'Endolift® Zürich – Laser-Straffung ohne OP | Perfect Shape',
    description: 'Endolift® in Zürich: minimalinvasive Laser-Straffung für Hals, Jawline, Doppelkinn & Knie – ohne Schnitte, ohne Narben. CHF 1800 pro Zone. Jetzt buchen.',
    h1: 'Endolift®',
    h1Accent: 'Straffung ohne Operation',
    lead: 'Minimalinvasive Laserbehandlung zur Straffung, Definition der Konturen und Verbesserung der Hautqualität. Ideal für Hals, Jawline/Doppelkinn sowie Körperzonen wie Knie – ohne Schnitte, ohne Narben.',
    card: 'Laserfaser-Straffung für Hals, Jawline, Doppelkinn & Knie.',
    image: 'endolift-zuerich',
    imageAlt: 'Endolift® Laserbehandlung am Hals und an der Jawline in Zürich',
    chips: ['ca. 45–60 Min.', 'Minimalinvasiv', 'Kurze Ausfallzeit'],
    intro: 'Endolift® gilt als eine der innovativsten Methoden zur Hautstraffung ohne Skalpell. Eine haarfeine Laserfaser arbeitet direkt unter der Haut – das strafft das Gewebe, definiert die Konturen und reduziert je nach Zone kleine Fettdepots. Bei Perfect Shape in Zürich arbeiten wir mit dem Original-Endolift®-System.',
    what: {
      title: 'Was ist Endolift®?',
      text: 'Endolift® ist eine minimalinvasive Laserbehandlung zur Hautstraffung und Konturverbesserung. Über eine ultradünne Laserfaser wird Energie präzise im Gewebe abgegeben – zur Anregung der Kollagenbildung und (je nach Zone) zur Reduktion kleiner Fettdepots.',
      bullets: ['Ohne Schnitte, ohne Narben', 'Gezielte Straffung & Definition der Konturen', 'Verbesserung von Hautstruktur und Spannkraft'],
    },
    indications: { title: 'Geeignete Zonen', items: ['Hals', 'Jawline & Doppelkinn', 'Knie'] },
    contra: { title: 'Ihre Vorteile', items: ['Minimalinvasiv – kein operatives Facelift', 'Kurze Erholungszeit', 'Natürlich wirkende Straffung durch Kollagen-Neubildung'], note: 'Eine individuelle Beratung klärt realistische Ziele und die optimale Zone.', positive: true },
    steps: [
      ['Beratung & Planung', 'Analyse der Zone, Aufklärung, Festlegung des Behandlungsziels.'],
      ['Behandlung', 'Präzise Laserenergie über eine feine Faser – Straffung und Konturierung.'],
      ['Nachsorge', 'Leichte Schwellung/Rötung möglich – kurze Downtime, je nach Zone.'],
    ],
    results: {
      title: 'Ergebnisse',
      items: ['Erste Straffung oft zeitnah sichtbar', 'Weitere Verbesserung über Wochen durch Kollagenaufbau', 'Definiertere Konturen und bessere Hautqualität'],
      note: '*Resultate sind individuell und hängen von Ausgangsbefund und Lebensstil ab.',
      stats: [['45–60', 'Minuten'], ['1', 'Zone pro Termin'], ['0', 'Schnitte & Narben']],
    },
    prices: [
      { name: '1 Zone – Jawline & Doppelkinn', desc: 'Konturierung der Kieferlinie und Reduktion des Doppelkinns für ein definierteres Profil.', price: 1800, featured: true },
      { name: '1 Zone – Hals', desc: 'Straffung der Halshaut und Verbesserung der Hautstruktur mittels minimalinvasiver Laserfaser.', price: 1800 },
      { name: '1 Zone – Knie', desc: 'Hautstraffung im Kniebereich zur Glättung und Verbesserung der Gewebespannung.', price: 1800 },
    ],
    priceNote: 'Eine persönliche Beratung ist empfohlen, um die optimale Zone und Zielsetzung festzulegen.',
    faq: [
      ['Ist Endolift® schmerzhaft?', 'Die Behandlung ist in der Regel gut tolerierbar. Empfindungen wie Wärme oder ein leichtes Ziehen sind möglich. Details besprechen wir im Beratungsgespräch.'],
      ['Wie lange dauert die Erholungszeit?', 'Oft ist man schnell wieder gesellschaftsfähig. Leichte Schwellungen oder Rötungen können kurzzeitig auftreten – abhängig von Zone und individueller Reaktion.'],
      ['Wann sehe ich Ergebnisse?', 'Ein erster Straffungseffekt kann zeitnah sichtbar sein. Die weitere Verbesserung entwickelt sich über mehrere Wochen, da die Kollagenbildung angeregt wird.'],
      ['Für wen ist Endolift® geeignet?', 'Für alle, die sich eine Straffung oder Konturierung ohne Operation wünschen. Im Beratungsgespräch prüfen wir Eignung, Erwartungen und Kontraindikationen individuell.'],
    ],
    related: ['fadenlifting-zuerich', 'rf-needling-zuerich', 'biostimulatoren-zuerich'],
  },
  {
    slug: 'rf-needling-zuerich',
    oldSlug: 'rf needling',
    category: 'apparativ',
    name: 'RF Needling',
    navName: 'RF Needling',
    keyword: 'RF Needling Zürich',
    title: 'RF Needling Zürich – Aknenarben & Poren | Perfect Shape',
    description: 'RF Needling in Zürich gegen Aknenarben, grosse Poren & feine Linien. Gesicht + Hals CHF 230, 4er-Kur CHF 850. Kurze Downtime – jetzt Termin buchen.',
    h1: 'RF Needling',
    h1Accent: 'Kollagen-Boost & Straffung',
    lead: 'Kombiniert Microneedling mit Radiofrequenz, um die Dermis gezielt zu erwärmen, Kollagen zu stimulieren und die Hautstruktur zu verfeinern – effektiv bei Poren, Aknenarben und feinen Linien, mit kurzer Downtime.',
    card: 'Radiofrequenz-Microneedling gegen Narben, Poren & feine Linien.',
    image: 'rf-needling-zuerich',
    imageAlt: 'RF Needling Behandlung im Gesicht in Zürich – Radiofrequenz-Microneedling',
    chips: ['45–60 Min.', 'Kur: 3–4 Sitzungen', 'Abstand 4–6 Wochen'],
    intro: 'RF Needling ist eine der wirksamsten Behandlungen der apparativen Kosmetik für ein sichtbar verfeinertes Hautbild. Die Kombination aus Microneedling und Radiofrequenz wirkt in der Tiefe – ideal bei Aknenarben, vergrösserten Poren und beginnender Hauterschlaffung.',
    what: {
      title: 'Was ist RF Needling?',
      text: 'RF Needling (Radiofrequenz-Microneedling) nutzt feine, vergoldete Nadeln, die kurze RF-Energieimpulse in die Dermis abgeben. So entstehen kontrollierte Mikrokanäle und eine thermische Stimulation, die die körpereigene Kollagen- und Elastinbildung anregt – für festere, glattere Haut ohne Volumenaufbau.',
      bullets: ['Verbesserung von Poren, Textur & feinen Linien', 'Reduktion von Aknenarben & leichten Dehnungsstreifen', 'Straffung von Wangen, Unterkieferkontur und Hals'],
    },
    indications: { title: 'Indikationen', items: ['Vergrösserte Poren, unruhige Hautstruktur', 'Aknenarben (atrophisch), Post-Akne', 'Feine Fältchen, leichte Hauterschlaffung', 'Hals, Dekolleté, Oberlippenbereich'] },
    contra: { title: 'Kontraindikationen', items: ['Akute Entzündung/Infektion im Behandlungsareal', 'Schwangerschaft/Stillzeit', 'Isotretinoin-Therapie (< 6 Monate)', 'Metallimplantate im Areal, aktiver Herpes'], note: STD_CONTRA_NOTE },
    steps: [
      ['Beratung & Planung', 'Indikationscheck, Areale, Tiefe & RF-Parameter, Anzahl Sitzungen.'],
      ['Vorbereitung', 'Reinigung, Betäubungscreme, Desinfektion.'],
      ['RF Needling', 'Fraktionierte Behandlung mit RF-Abgabe in definierter Tiefe.'],
      ['Abschluss & Nachsorge', 'Beruhigende Pflege, Sonnenschutz (SPF 50), 24–48 h Sport/Sauna meiden.'],
    ],
    results: {
      title: 'Ergebnisse & Haltbarkeit',
      items: ['Soforteffekt: praller, glatterer Teint („Glow“)', 'Strukturaufbau (Kollagen/Elastin) über 6–12 Wochen', 'Kur von 3–4 Sitzungen empfohlen'],
      note: '*Leichte Rötung 0–24 h möglich; Make-up meist am Folgetag.',
      stats: [['45–60', 'Minuten'], ['3–4', 'Sitzungen (Kur)'], ['6–12', 'Wochen Kollagenaufbau']],
    },
    prices: [
      { name: '4× RF Needling Kur', desc: 'Intensivkur mit nachhaltigem Lifting- und Regenerationseffekt.', price: 850, featured: true },
      { name: 'RF Needling Gesicht + Hals', desc: 'Kombination aus Microneedling und Radiofrequenz zur Hautstraffung und Verbesserung der Struktur.', price: 230 },
    ],
    faq: [
      ['Wie viele Sitzungen brauche ich?', 'Meist empfehlen wir eine Kur von 3–4 Sitzungen im Abstand von 4–6 Wochen. Auffrischungen nach 6–12 Monaten halten den Effekt stabil.'],
      ['Ist die Behandlung schmerzhaft?', 'Dank Betäubungscreme ist RF Needling gut tolerierbar. Direkt danach kann es warm oder prickelnd sein und die Haut ist 1–3 Tage leicht gerötet.'],
      ['Was ist nach der Behandlung wichtig?', '24–48 Stunden Sport und Hitze vermeiden, sanfte Pflege, täglich SPF 50. Retinoide und Säuren erst wieder einsetzen, wenn sich die Haut beruhigt hat.'],
    ],
    related: ['microdermabrasion-zuerich', 'carbon-laser-peeling-zuerich', 'endolift-zuerich'],
  },
  {
    slug: 'microdermabrasion-zuerich',
    oldSlug: 'micodermabrasion',
    category: 'apparativ',
    name: 'Microdermabrasion',
    navName: 'Microdermabrasion',
    keyword: 'Microdermabrasion Zürich',
    title: 'Microdermabrasion Zürich – Glow & Poren | Perfect Shape',
    description: 'Microdermabrasion in Zürich: sanfte Tiefenreinigung für feinere Poren und sofortigen Glow – ohne Ausfallzeit. CHF 145. Jetzt online Termin buchen.',
    h1: 'Microdermabrasion',
    h1Accent: 'Sofort-Glow & feine Poren',
    lead: 'Sanftes, kontrolliertes Abtragen der obersten Hornschicht mit feinen Kristallen bzw. Diamantaufsätzen. Regt die Zellerneuerung an, glättet die Oberfläche und erhöht die Aufnahme von Wirkstoffen.',
    card: 'Tiefenreinigung für feinere Poren & sofortigen Glow.',
    image: 'microdermabrasion-zuerich',
    imageAlt: 'Microdermabrasion Tiefenreinigung im Gesicht in Zürich',
    chips: ['30–45 Min.', 'Kur: 3–6 Sitzungen', 'Keine Ausfallzeit'],
    intro: 'Die Microdermabrasion ist die perfekte Behandlung für einen frischen, ebenmässigen Teint – ob vor einem besonderen Anlass oder als regelmässige Pflege-Kur. Sanft, ohne Ausfallzeit und mit sofort sichtbarem Ergebnis.',
    what: {
      title: 'Was ist Microdermabrasion?',
      text: 'Bei der Microdermabrasion wird die oberste Hornschicht (Stratum corneum) gleichmässig entfernt. Das verfeinert die Hautstruktur, reduziert Rauigkeit und unterstützt die Zellregeneration. In Kombination mit aufbauenden Seren lassen sich die Resultate zusätzlich verstärken.',
      bullets: ['Sofort sichtbarer Glow & glatteres Hautgefühl', 'Feinere Poren, ebenmässigerer Teint', 'Bessere Aufnahme nachfolgender Wirkstoffe'],
    },
    indications: { title: 'Indikationen', items: ['Müder, fahler Teint', 'Unruhige Textur, raue Partien', 'Vergrösserte/verstopfte Poren', 'Feine Linien, Trockenheitsfältchen'] },
    contra: { title: 'Kontraindikationen', items: ['Aktive Akne/Entzündungen, Herpes', 'Ekzeme, Rosazea-Schub, frische Wunden', 'Isotretinoin-Therapie (< 6 Monate)', 'Unverträglichkeit gegen verwendete Produkte'], note: 'Die Eignung wird vor Ort individuell geprüft.' },
    steps: [
      ['Beratung & Hautanalyse', 'Hautzustand, Ziele und passende Intensität/Seren festlegen.'],
      ['Vorbereitung', 'Reinigung & Desinfektion, ggf. Enzym-Peeling.'],
      ['Microdermabrasion', 'Gleichmässige Abtragung, angepasst an Areal & Empfindlichkeit.'],
      ['Beruhigung & Schutz', 'Aufbau-Seren, Feuchtigkeit, Abschlusspflege & SPF 50.'],
    ],
    results: {
      title: 'Ergebnisse & Haltbarkeit',
      items: ['Sofort frischerer, ebenmässigerer Teint', 'Verfeinerte Poren & bessere Wirkstoffaufnahme', 'Für nachhaltigen Effekt: 3–6 Sitzungen als Kur'],
      note: '*Kurzzeitige Rötung möglich; meist sofort alltagsfähig.',
      stats: [['30–45', 'Minuten'], ['3–6', 'Sitzungen (Kur)'], ['0', 'Tage Downtime']],
    },
    prices: [
      { name: 'Microdermabrasion (Tiefenreinigung)', desc: 'Sanftes, tiefenreinigendes Peeling für ein ebenmässiges, frisches Hautbild.', price: 145, featured: true },
    ],
    faq: [
      ['Für welche Hauttypen ist die Behandlung geeignet?', 'Für die meisten Hauttypen – besonders bei rauer Textur, verstopften Poren und fahl wirkender Haut. Nicht geeignet bei aktiver Entzündung, Herpes, Ekzem-Schub oder Rosazea in der Akutphase.'],
      ['Gibt es Ausfallzeit?', 'In der Regel keine. Kurzzeitige Rötung oder Empfindlichkeit sind möglich. Sport, Sauna und starke Sonne 24 Stunden meiden; täglich SPF 50.'],
      ['Kann ich die Microdermabrasion mit anderen Behandlungen kombinieren?', 'Ja. Häufige Kombinationen sind Mesotherapie oder ein Fruchtsäure-Peeling. Wir beraten Sie gerne zu sinnvoller Reihenfolge und Abständen.'],
    ],
    related: ['carbon-laser-peeling-zuerich', 'fruchtsaeure-peeling-zuerich', 'rf-needling-zuerich'],
  },
  {
    slug: 'carbon-laser-peeling-zuerich',
    oldSlug: 'carbon laser peeling',
    category: 'apparativ',
    name: 'Carbon Laser Peeling',
    navName: 'Carbon Laser Peeling',
    keyword: 'Carbon Laser Peeling Zürich',
    title: 'Carbon Laser Peeling Zürich – Hollywood Peel | Perfect Shape',
    description: 'Carbon Laser Peeling („Hollywood Peel“) in Zürich: porenfeine, klare Haut & sofortiger Glow ohne Ausfallzeit. Gesicht ab CHF 200. Jetzt buchen.',
    h1: 'Carbon Laser Peeling',
    h1Accent: 'der Hollywood Peel',
    lead: 'Eine Carbon-Lotion bindet Talg und Hornschüppchen, der Laser verdampft die Schicht schonend: Poren werden gereinigt, die Textur verfeinert – für sofortigen Glow. Ideal bei Mischhaut und vergrösserten Poren.',
    card: 'Der „Hollywood Peel“ für porenfeine, klare Haut.',
    image: 'carbon-laser-peeling-zuerich',
    imageAlt: 'Carbon Laser Peeling – Hollywood Peel Behandlung in Zürich',
    chips: ['30–45 Min.', 'Kur: 3–5 Sitzungen', 'Downtime 0–1 Tag'],
    intro: 'Das Carbon Laser Peeling – bekannt als „Hollywood Peel“ – ist das ideale Treatment vor besonderen Anlässen. Es verfeinert die Poren, mattiert die Haut und sorgt für einen strahlend klaren Teint, praktisch ohne Ausfallzeit.',
    what: {
      title: 'Was ist Carbon Laser Peeling?',
      text: 'Beim Carbon Laser Peeling wird eine feine Kohlenstoff-Lotion aufgetragen, die sich an Talg, Schüppchen und Verunreinigungen anlagert. Der anschliessende Q-switched Laser verdampft diese Schicht punktgenau, reinigt die Poren und stimuliert zugleich die Hauterneuerung.',
      bullets: ['Sofort sichtbarer Glow & porenfeineres Erscheinungsbild', 'Mattierung, glattere Textur, weniger Mitesser', 'Schonend, kaum Ausfallzeit'],
    },
    indications: { title: 'Indikationen', items: ['Erweiterte Poren, fettige T-Zone', 'Unruhige/raue Textur, Mitesser', 'Post-Akne-Unregelmässigkeiten, Pigmentflecken', 'Teint-Auffrischung vor Events'] },
    contra: { title: 'Kontraindikationen', items: ['Aktive Entzündungen/Herpes im Behandlungsareal', 'Frischer Sonnenbrand, kürzliches starkes Peeling', 'Isotretinoin-Therapie (< 6 Monate)', 'Schwangerschaft/Stillzeit (individuell)'], note: 'Die Eignung wird vor Ort individuell beurteilt.' },
    steps: [
      ['Beratung & Auswahl', 'Hautanalyse, Indikations-Check und Festlegung der Parameter.'],
      ['Reinigung & Carbon-Lotion', 'Schonende Reinigung, Auftragen der Carbon-Suspension.'],
      ['Laser-Durchgang', 'Der Laser verdampft die Carbon-Schicht selektiv und klärt die Poren.'],
      ['Beruhigung & Schutz', 'Kühlung, Feuchtigkeit, ggf. Seren und Abschluss mit SPF 50.'],
    ],
    results: {
      title: 'Ergebnisse & Haltbarkeit',
      items: ['Soforteffekt: matter, reiner, feiner wirkender Teint', 'Reduziert Talg & verfeinert Poren über mehrere Wochen', 'Empfohlen: 3–5 Sitzungen im Abstand von 2–4 Wochen'],
      note: '*Downtime minimal (0–1 Tag); leichte Rötung möglich.',
      stats: [['30–45', 'Minuten'], ['3–5', 'Sitzungen (Kur)'], ['0–1', 'Tage Downtime']],
    },
    prices: [
      { name: 'Gesicht', desc: 'Verfeinert Poren, reduziert Pigmentflecken und stimuliert die Kollagenproduktion.', price: 200, featured: true },
      { name: 'Gesicht & Hals', desc: 'Effektive Hautauffrischung für Gesicht und Hals in einer Sitzung.', price: 230 },
      { name: 'Hände', desc: 'Aufhellung und Glättung der Haut an den Händen für ein ebenmässigeres Aussehen.', price: 130 },
    ],
    faq: [
      ['Habe ich Ausfallzeit?', 'In der Regel nicht. Kurzzeitige Rötung ist möglich. 24 Stunden starke Sonne, Sauna und intensiven Sport vermeiden; täglich SPF 50.'],
      ['Für wen eignet sich das Carbon Peeling besonders?', 'Ideal bei Mischhaut, vergrösserten Poren, Mitessern und fahlem Teint. Bei akuter Entzündung, Herpes oder frischem Sonnenbrand raten wir zunächst ab.'],
      ['Kann man das Peeling mit anderen Treatments kombinieren?', 'Ja – z. B. mit Microdermabrasion oder leichten Fruchtsäuren. Wir beraten zur sinnvollen Reihenfolge und zu den Abständen.'],
    ],
    related: ['microdermabrasion-zuerich', 'fruchtsaeure-peeling-zuerich', 'laser-haarentfernung-zuerich'],
  },
  {
    slug: 'klassische-massage-zuerich',
    oldSlug: 'classic massage',
    category: 'massage',
    name: 'Classic Massage',
    navName: 'Klassische Massage',
    keyword: 'Massage Zürich',
    title: 'Massage Zürich – Klassisch & Lymphdrainage | Perfect Shape',
    description: 'Klassische Massage & Lymphdrainage in Zürich an der Bahnhofstrasse: löst Verspannungen, reduziert Stress. 55 Min. CHF 120. Jetzt online buchen.',
    h1: 'Klassische Massage',
    h1Accent: 'Entspannung & Lockerung',
    lead: 'Klassische Teil- oder Ganzkörpermassage zur Lösung von Muskelverspannungen, Förderung der Durchblutung und Beruhigung des Nervensystems. Ideal bei Nacken-/Rückenbeschwerden, Stress und Müdigkeit.',
    card: 'Löst Verspannungen, senkt Stress – inkl. Lymphdrainage.',
    image: 'klassische-massage-zuerich',
    imageAlt: 'Klassische Rückenmassage in Zürich – Entspannung bei Perfect Shape',
    chips: ['55 Min.', 'Einzeln oder als Kur', 'Keine Downtime'],
    intro: 'Eine Auszeit mitten in Zürich: Unsere klassische Massage löst Verspannungen in Nacken, Schultern und Rücken und schenkt Ihnen spürbar neue Energie – perfekt nach einem langen Arbeitstag oder intensivem Training. Wir massieren mit fachlichem Know-how aus Sportwissenschaft und Lymphdrainage.',
    what: {
      title: 'Was ist die klassische Massage?',
      text: 'Die klassische Massage (schwedische Massage) nutzt Griffe wie Streichungen, Knetungen, Reibungen und Dehnungen. Sie löst muskuläre Verhärtungen, verbessert die Mikrozirkulation und unterstützt Regeneration sowie Stressabbau – wahlweise als Teil- oder Ganzkörperbehandlung.',
      bullets: ['Löst Verspannungen & verbessert die Beweglichkeit', 'Fördert Durchblutung & Stoffwechsel', 'Stressreduktion, besserer Schlaf & Wohlbefinden'],
    },
    indications: { title: 'Indikationen', items: ['Nacken-, Schulter- & Rückenverspannungen', 'Sitzende Tätigkeit, Bildschirmarbeit', 'Muskuläre Überlastung nach Sport', 'Stress, innere Unruhe'] },
    contra: { title: 'Kontraindikationen', items: ['Akute Entzündungen, Fieber, Infekte', 'Frische Verletzungen/Operationen, akute Thrombose', 'Offene Hautläsionen, starke Hämatome', 'Ungeklärte Schmerzen – vorher ärztlich abklären'], note: 'Eignung & Intensität werden individuell vor Ort festgelegt.' },
    steps: [
      ['Anamnese & Zielsetzung', 'Kurze Befragung zu Beschwerden, Intensitätswunsch und Fokusregionen.'],
      ['Vorbereitung', 'Bequeme Lagerung, auf Wunsch aromatisches Massageöl.'],
      ['Massage', 'Klassische Griffabfolge, Druckstärke wird laufend abgestimmt.'],
      ['Nachruhe & Empfehlungen', 'Kurze Nachruhe, Trinkempfehlung, Tipps für zu Hause.'],
    ],
    results: {
      title: 'Ergebnisse & Wirkung',
      items: ['Sofort spürbare Entspannung & bessere Durchblutung', 'Löst muskuläre Verspannungen & reduziert Stress', 'Für nachhaltige Wirkung: regelmässig (wöchentlich/14-täglich)'],
      note: '*Keine Ausfallzeit; an individuelle Bedürfnisse anpassbar.',
      stats: [['55', 'Minuten'], ['1×', 'pro Woche bei Beschwerden'], ['0', 'Tage Downtime']],
    },
    prices: [
      { name: 'Klassische Massage', detail: '55 Min.', desc: 'Entspannende Ganzkörpermassage zur Lockerung der Muskulatur und Stressreduktion.', price: 120, featured: true },
      { name: 'Lymphdrainage', desc: 'Sanfte manuelle Technik zur Förderung des Lymphflusses und Entstauung des Gewebes.', price: 120 },
    ],
    faq: [
      ['Tut die klassische Massage weh?', 'Sie darf „angenehm intensiv“ sein, jedoch nicht schmerzhaft. Wir passen die Druckstärke jederzeit an – geben Sie uns einfach Feedback.'],
      ['Gibt es eine Downtime?', 'In der Regel nicht. Leichte Nachmüdigkeit oder Muskelkater können auftreten – viel trinken, moderate Bewegung empfohlen.'],
      ['Wie oft sollte ich kommen?', 'Bei akuten Verspannungen 1× pro Woche für 3–4 Wochen. Zur Erhaltung alle 2–4 Wochen oder bei Bedarf.'],
    ],
    related: ['anti-cellulite-massage-zuerich', 'mesotherapie-zuerich', 'laser-haarentfernung-zuerich'],
  },
  {
    slug: 'anti-cellulite-massage-zuerich',
    oldSlug: 'anti-cellulite massage',
    category: 'massage',
    name: 'Anti-Cellulite Massage',
    navName: 'Anti-Cellulite & Maderotherapie',
    keyword: 'Anti-Cellulite Massage Zürich',
    title: 'Anti-Cellulite Massage Zürich | Perfect Shape',
    description: 'Anti-Cellulite Massage & Maderotherapie in Zürich für glattere Haut an Beinen & Po. Ab CHF 120, 10er-Abo CHF 1350. Jetzt Termin online buchen.',
    h1: 'Anti-Cellulite Massage',
    h1Accent: 'glattere Konturen',
    lead: 'Spezielle Grifftechniken, rhythmische Knetungen und Drainagegriffe regen die Mikrozirkulation an, unterstützen den Lymphfluss und lockern verklebte Gewebestrukturen – für sichtbar glattere Haut an Oberschenkeln und Gesäss.',
    card: 'Massage & Maderotherapie für glattere Haut an Beinen & Po.',
    image: 'anti-cellulite-massage-zuerich',
    imageAlt: 'Anti-Cellulite Massage an den Beinen in Zürich',
    chips: ['45–55 Min.', 'Kur: 6–10 Sitzungen', '1–2× pro Woche'],
    intro: 'Cellulite ist kein Schönheitsfehler – aber viele Frauen wünschen sich glattere, straffere Haut. Unsere Anti-Cellulite Massage und die Maderotherapie (Holztherapie) setzen genau dort an. Agnieszka Jaggy ist Ernährungsberaterin mit Schwerpunkt Cellulite und begleitet Sie auch mit Tipps für den Alltag.',
    what: {
      title: 'Was ist die Anti-Cellulite Massage?',
      text: 'Die Anti-Cellulite Massage kombiniert tiefgreifende Knetungen, Scher- und Rollgriffe mit drainageorientierten Techniken. Ziel ist es, die Mikrozirkulation zu fördern, Wasseransammlungen zu verringern und die Gewebespannung positiv zu beeinflussen. Optional kommen Schröpf- oder Holztools (Maderotherapie) zum Einsatz.',
      bullets: ['Fördert Lymphfluss & Durchblutung', 'Lockert Verklebungen & verbessert das Hautbild', 'Unterstützt Kontur & Wohlgefühl im Alltag'],
    },
    indications: { title: 'Indikationen', items: ['Orangenhaut an Oberschenkeln, Gesäss, Hüften', 'Schwere Beine, Neigung zu Wassereinlagerungen', 'Nachlassende Gewebespannung', 'Als Ergänzung zu Sport & ausgewogener Ernährung'] },
    contra: { title: 'Kontraindikationen', items: ['Akute Entzündungen, Fieber, Infektionen', 'Krampfadern/Thrombosen, Gefässerkrankungen', 'Frische OPs/Verletzungen, Hämatomneigung', 'Schwangerschaft – nur nach Rücksprache'], note: 'Eignung & Intensität werden individuell vor Ort festgelegt.' },
    steps: [
      ['Analyse & Zieldefinition', 'Check der Areale & Abstimmung von Intensität und Kurplan.'],
      ['Vorbereitung', 'Bequeme Lagerung; optional wärmendes Gel/Öl.'],
      ['Behandlung', 'Knet-, Scher- und Rollgriffe, Lymphdrainage; optional Holztools.'],
      ['Nachpflege & Kur', 'Kurplan, Trinkempfehlung, Bewegungs- und Selbstmassage-Tipps.'],
    ],
    results: {
      title: 'Ergebnisse & Verlauf',
      items: ['Verbessert Mikrozirkulation & Lymphfluss', 'Glatter wirkende Haut bei regelmässiger Anwendung', 'Kur: 6–10 Sitzungen, danach Erhaltungsintervalle'],
      note: '*Bewegung & ausreichend Flüssigkeit unterstützen das Ergebnis.',
      stats: [['45–55', 'Minuten'], ['6–10', 'Sitzungen (Kur)'], ['1–2×', 'pro Woche']],
    },
    prices: [
      { name: '10er-Abo Anti-Cellulite', desc: 'Intensivkur für sichtbare und langanhaltende Ergebnisse.', price: 1350, featured: true },
      { name: 'Anti-Cellulite Massage', detail: '55 Min.', desc: 'Straffende Massage zur Reduktion von Cellulite und Verbesserung der Hautstruktur.', price: 145 },
      { name: 'Maderotherapie', detail: '45 Min.', desc: 'Spezielle Holztherapie zur Anregung des Stoffwechsels und Glättung des Hautbildes.', price: 120 },
    ],
    faq: [
      ['Ist die Behandlung schmerzhaft?', 'Die Massage ist kräftig, sollte aber gut tolerierbar sein. Die Intensität stimmen wir individuell mit Ihnen ab.'],
      ['Brauche ich zwingend eine Kur?', 'Einzeltermine sind möglich. Für sichtbare und stabile Effekte empfehlen wir jedoch eine Kur von 6–10 Sitzungen, 1–2× pro Woche – z. B. mit unserem 10er-Abo.'],
      ['Was kann ich selbst beitragen?', 'Regelmässige Bewegung, ausgewogene Ernährung, ausreichend Trinken und eine kurze tägliche Selbstmassage unterstützen das Ergebnis nachhaltig.'],
    ],
    related: ['klassische-massage-zuerich', 'mesotherapie-zuerich', 'endolift-zuerich'],
  },
  {
    slug: 'fruchtsaeure-peeling-zuerich',
    oldSlug: 'fruchtsaure behandlung',
    category: 'peeling',
    name: 'Fruchtsäure Behandlung',
    navName: 'Fruchtsäure & PRX-T33',
    keyword: 'Fruchtsäurepeeling Zürich',
    title: 'Fruchtsäurepeeling Zürich – PRX-T33 Peeling | Perfect Shape',
    description: 'Fruchtsäure-Behandlung & PRX-T33 Peeling in Zürich: ebenmässiger Teint, feine Poren und Glow – ohne Schälung. CHF 180. Jetzt Termin buchen.',
    h1: 'Fruchtsäure-Behandlung',
    h1Accent: 'ebenmässiger Teint',
    lead: 'Kontrollierte chemische Peelings mit AHA/BHA lösen schonend verhornte Zellen, fördern die Erneuerung und lassen den Teint frischer, glatter und gleichmässiger erscheinen – ideal bei fahler Haut, feinen Linien und Unreinheiten.',
    card: 'AHA/BHA & PRX-T33 – Glow ohne Schälung.',
    image: 'fruchtsaeure-peeling-zuerich',
    imageAlt: 'Fruchtsäure-Peeling im Gesicht in Zürich – PRX-T33 Behandlung',
    chips: ['30–45 Min.', 'Kur: 3–6 Sitzungen', 'Abstand 2–4 Wochen'],
    intro: 'Ein professionelles Fruchtsäurepeeling ist der schnellste Weg zu einem klareren, strahlenderen Hautbild. Besonders beliebt ist unser PRX-T33 Peeling: Es biorevitalisiert die Haut intensiv – ganz ohne sichtbares Schälen.',
    what: {
      title: 'Was ist eine Fruchtsäure-Behandlung?',
      text: 'Bei der Fruchtsäure-Behandlung (AHA/BHA-Peeling) werden – je nach Hauttyp – milde bis mittlere Säuren (z. B. Glykol-, Milch-, Mandel- oder Salicylsäure) zeitkontrolliert aufgetragen. Das löst Verhornungen, verfeinert die Poren und fördert ein gleichmässiges Hautbild. Konzentration und Einwirkzeit werden individuell gewählt.',
      bullets: ['Glow & glattere Hautoberfläche', 'Verfeinerte Poren, ebenmässiger Teint', 'Hilft bei Unreinheiten & leichten Pigmentstörungen'],
    },
    indications: { title: 'Indikationen', items: ['Fahler Teint, Rauigkeit', 'Vergrösserte Poren, Unreinheiten', 'Feine Linien, erste Lichtschäden', 'Leichte Pigmentflecken/Post-Akne-Spuren'] },
    contra: { title: 'Kontraindikationen', items: ['Aktive Entzündungen/Infektionen, offene Stellen', 'Akuter Herpes, starke Rosazea/Ekzem-Schübe', 'Schwangerschaft/Stillzeit (nur sehr sanfte Varianten)', 'Retinoid-Therapie (Absprache nötig)'], note: 'Säuretyp & Stärke werden vor Ort individuell festgelegt.' },
    steps: [
      ['Anamnese & Hautanalyse', 'Check von Hautzustand, Zielsetzung & Auswahl des Peelings.'],
      ['Vorbereitung', 'Reinigung & Entfettung; Schutz empfindlicher Areale.'],
      ['Peeling & Neutralisation', 'Auftragen des Peelings mit genauer Zeitkontrolle.'],
      ['Abschluss & Pflege', 'Beruhigende Pflege, SPF-Hinweise, Kurplanung.'],
    ],
    results: {
      title: 'Ergebnisse & Haltbarkeit',
      items: ['„Glow“ & verfeinerte Poren nach wenigen Tagen', 'Gleichmässigeres Hautbild über 2–6 Wochen', 'Kur von 3–6 Sitzungen (je nach Stärke des Peelings)'],
      note: '*Kurzzeitige Rötung möglich; SPF 50 konsequent verwenden.',
      stats: [['30–45', 'Minuten'], ['3–6', 'Sitzungen (Kur)'], ['2–4', 'Wochen Abstand']],
    },
    prices: [
      { name: 'PRX-T33 Peeling', desc: 'Biorevitalisierendes Peeling ohne Schälung – für ein frisches, strahlendes Hautbild.', price: 180, featured: true },
    ],
    faq: [
      ['Gibt es eine Ausfallzeit?', 'Meist nicht. Kurzzeitige Rötung oder leichtes Prickeln sind möglich; je nach Stärke kann es in den Folgetagen zu feiner Schuppung kommen.'],
      ['Was muss ich nach dem Peeling beachten?', '24–48 Stunden kein intensiver Sport, keine Sauna, kein Solarium. Täglich hoher Lichtschutz und milde Pflege; Retinoide und starke Säuren zunächst pausieren.'],
      ['Für wen ist die Kur sinnvoll?', 'Bei fahlem Teint, grossen Poren, Unreinheiten oder leichten Pigmentstörungen. Bei aktiver Akne oder Rosazea wählen wir sanftere Protokolle.'],
    ],
    related: ['microdermabrasion-zuerich', 'carbon-laser-peeling-zuerich', 'mesotherapie-zuerich'],
  },
];

export const TEAM = [
  {
    name: 'Dr. med. Roya Jeyrani',
    role: 'Fachärztin für Radiologie · Ästhetische Medizin',
    roleShort: 'Ärztin für ästhetische Medizin',
    image: 'dr-med-roya-jeyrani',
    alt: 'Dr. med. Roya Jeyrani – Ärztin für ästhetische Medizin in Zürich',
    bio: [
      'Nach dem Medizinstudium in Hamburg (2001) startete Roya ihre Facharztausbildung in der Radiologie in Essen. 2005 setzte sie ihre Ausbildung am Inselspital in Bern fort, erlangte 2007 den Facharzttitel für Radiologie und im Folgejahr den Doktortitel.',
      'In der ästhetischen Medizin hat sie ihre Passion entdeckt. Sie hat zahlreiche Kurse absolviert und arbeitet seit vielen Jahren in der medizinischen Ästhetik. Regelmässige Fortbildungen helfen ihr, Patientinnen und Patienten stets das Beste anzubieten.',
      '2018 nahm sie an einer Fortbildung in Seoul teil, um sich mit den neuesten Methoden und Trends des Liftings mit selbstauflösenden Fäden vertraut zu machen.',
    ],
    facts: ['Medizinstudium Hamburg', 'Facharzttitel Radiologie (Inselspital Bern)', 'Fortbildung Fadenlifting, Seoul 2018'],
  },
  {
    name: 'Agnieszka Jaggy',
    role: 'Medizinisch-kosmetische Therapeutin · Laserschutzbeauftragte',
    roleShort: 'Med.-kosmetische Therapeutin',
    image: 'agnieszka-jaggy',
    alt: 'Agnieszka Jaggy – medizinisch-kosmetische Therapeutin bei Perfect Shape Zürich',
    bio: [
      'Heilpraktikerin (i. A.) und medizinisch-kosmetische Therapeutin mit Weiterbildung im Bereich der apparativen Kosmetik (Kavitation, Stosswellentherapie, RF Needling, HIFU Ultraschall, Kryolipolyse).',
      'Diplomierte Sportwissenschaftlerin mit Kursen in Sportmedizin (Lymphdrainage, Rückenschule) und Ernährungsberaterin mit Schwerpunkt Cellulite. Zertifizierte Laserschutzbeauftragte für die Arbeit mit Diodenlaser.',
    ],
    facts: ['Zertifizierte Laserschutzbeauftragte', 'Dipl. Sportwissenschaftlerin', 'Ernährungsberaterin (Schwerpunkt Cellulite)'],
  },
];

export const REVIEWS = [
  {
    name: 'Ilona M.',
    text: 'Agnieszka begleitet mich schon seit vielen Jahren – und ich würde niemand anderem mehr vertrauen! Wir haben meine Lippen gemeinsam ganz sanft und natürlich aufgebaut. Sie hört zu, berät ehrlich und schaut immer, was wirklich zu mir passt. Ich schätze besonders, dass sie nie etwas „verkauft“, sondern offen sagt, wenn etwas nicht zu mir passt. Dank ihr fühle ich mich jedes Mal schön und wohl in meiner Haut.',
    tag: 'Lippenaufbau mit Hyaluron',
  },
  {
    name: 'Leta d. R.',
    text: 'I’ve exclusively been going to Agnieszka for over 3 years and haven’t looked back! What I appreciate is that they don’t oversell – if you want something that might not work best for your skin, age or condition, they will honestly advise you against it. The work is top-notch quality and prices are fair. A reliable and highly professional clinic. I recommend them!',
    tag: 'Stammkundin seit über 3 Jahren',
  },
];

export const HOME_FAQ = [
  ['Sieht das Ergebnis natürlich aus?', 'Ja – das ist unser Anspruch. Wir arbeiten dosiert und typgerecht und raten ehrlich ab, wenn eine Behandlung nicht zu Ihnen passt. Ziel ist, dass Sie frischer aussehen – nicht „gemacht“.'],
  ['Ist die Behandlung schmerzhaft?', 'Die meisten Behandlungen sind gut verträglich. Wo sinnvoll, verwenden wir eine Betäubungscreme oder Kühlung. Vorab besprechen wir genau, was Sie spüren werden.'],
  ['Bin ich nach der Behandlung direkt wieder gesellschaftsfähig?', 'Bei vielen Behandlungen ja – sofort oder nach wenigen Stunden. Leichte Rötungen oder Schwellungen sind je nach Methode möglich und klingen meist innert weniger Tage ab. Details finden Sie auf der jeweiligen Behandlungsseite.'],
  ['Wo befindet sich Perfect Shape Zürich?', 'Unser Studio befindet sich an der Bahnhofstrasse 94 (2. Etage) in 8001 Zürich – nur wenige Gehminuten vom Hauptbahnhof Zürich entfernt und bestens mit Tram, Bahn und zu Fuss erreichbar.'],
  ['Wie kann ich einen Termin buchen?', 'Am schnellsten online – rund um die Uhr über unser Buchungssystem. Alternativ erreichen Sie uns telefonisch unter +41 76 608 61 61, per WhatsApp oder per E-Mail.'],
  ['Wer führt die Behandlungen durch?', 'Diagnostik und Behandlungen werden von geprüften Ärzten und qualifizierten Spezialistinnen durchgeführt – darunter Dr. med. Roya Jeyrani und Agnieszka Jaggy, zertifizierte Laserschutzbeauftragte.'],
  ['Was kostet eine Behandlung?', 'Auf unserer Preisseite finden Sie transparente Richtpreise für alle Behandlungen – z. B. Laser-Haarentfernung ab CHF 40, Lippenaufbau ab CHF 160 oder Fadenlifting ab CHF 240. Die finalen Kosten legen wir nach der individuellen Beratung fest.'],
  ['Kann ich einen Termin verschieben oder absagen?', 'Ja, bis spätestens 24 Stunden vor dem Termin kostenlos. Bei kurzfristiger Absage oder Nichterscheinen berechnen wir eine Gebühr von CHF 50.'],
  ['Wie kann ich bezahlen?', 'Die Zahlung erfolgt direkt nach der Behandlung in bar, per Karte oder mit TWINT.'],
];

export const AGB = [
  ['1. Geltungsbereich', 'Diese Allgemeinen Geschäftsbedingungen (AGB) gelten für alle Dienstleistungen, Behandlungen, Angebote und Verkäufe von Perfect Shape Zürich, unabhängig davon, ob sie online, telefonisch oder persönlich gebucht oder erworben werden. Abweichende Vereinbarungen gelten nur, wenn sie schriftlich bestätigt wurden.'],
  ['2. Terminvereinbarung und Stornierungen', 'Termine können telefonisch, online oder vor Ort vereinbart werden. Eine Stornierung oder Verschiebung muss spätestens 24 Stunden vor dem Termin erfolgen. Bei kurzfristiger Absage (unter 24 Stunden) oder Nichterscheinen wird eine Gebühr von CHF 50 berechnet. Bei verspätetem Erscheinen kann die Behandlungszeit verkürzt werden, ohne Preisnachlass.'],
  ['3. Gesundheitliche Voraussetzungen', 'Der Kunde ist verpflichtet, das Personal von Perfect Shape Zürich vor Behandlungsbeginn über alle relevanten gesundheitlichen Probleme, Allergien, Hautkrankheiten, Schwangerschaft oder medizinische Behandlungen zu informieren. Perfect Shape Zürich übernimmt keine Haftung für Folgen, die durch unvollständige oder falsche Angaben entstehen.'],
  ['4. Preise und Zahlungsbedingungen', 'Alle Preise verstehen sich in Schweizer Franken (CHF) inkl. Mehrwertsteuer. Preisänderungen bleiben vorbehalten. Massgeblich sind die am Buchungstag gültigen Preise. Die Zahlung erfolgt unmittelbar nach der Behandlung in bar, per Karte oder TWINT. Bei Online-Buchungen kann eine Vorauszahlung verlangt werden.'],
  ['5. Haftung und Verantwortung', 'Die Behandlungen bei Perfect Shape Zürich dienen der Schönheit, Entspannung und dem Wohlbefinden. Sie ersetzen keine medizinische oder therapeutische Behandlung. Perfect Shape Zürich übernimmt keine Haftung für direkte oder indirekte Schäden, die durch unsachgemässe Nachsorge, Nichtbeachtung von Empfehlungen oder Eigenverschulden entstehen.'],
  ['6. Datenschutz', 'Personenbezogene Daten werden vertraulich behandelt und ausschliesslich zur Abwicklung von Buchungen, Rechnungen und Kundenpflege verwendet. Es erfolgt keine Weitergabe an Dritte ohne ausdrückliche Zustimmung des Kunden. Die erhobenen Daten werden nur so lange gespeichert, wie es zur Erfüllung des jeweiligen Zwecks erforderlich ist oder gesetzliche Vorschriften es verlangen. Der Kunde hat das Recht, Auskunft über die gespeicherten Daten zu verlangen sowie deren Berichtigung oder Löschung zu beantragen. Weitere Informationen finden Sie in unserer Datenschutzerklärung.'],
  ['7. Änderungen der Leistungen oder Öffnungszeiten', 'Perfect Shape Zürich behält sich das Recht vor, Öffnungszeiten, Leistungen oder Preise jederzeit anzupassen, sofern dies betriebsbedingt erforderlich ist.'],
  ['8. Salvatorische Klausel', 'Sollten einzelne Bestimmungen dieser AGB unwirksam sein, bleibt die Gültigkeit der übrigen Bestimmungen unberührt.'],
  ['9. Gerichtsstand und anwendbares Recht', 'Es gilt ausschliesslich schweizerisches Recht. Gerichtsstand für alle Streitigkeiten ist Zürich.'],
];

// Bilder der Startseite – zum Austauschen einfach den Bildnamen ändern (Dateien in assets/img, siehe README)
export const HOME = {
  heroImage: 'aesthetik-klinik-zuerich-hero', // + automatisch 'aesthetik-klinik-zuerich-hero-portrait' für Smartphones
  heroAlt: 'Entspannte Frau im hellen Studio von Perfect Shape mit Blick über Zürich',
  heroPos: '50% 30%',
  heroPosMobile: '50% 50%',
  bandImage: 'studio-perfect-shape-zuerich-empfang',
  bandAlt: 'Studio von Perfect Shape an der Bahnhofstrasse 94 in Zürich',
  ctaImage: 'rf-needling-zuerich',
  ctaAlt: 'Entspannte Behandlung bei Perfect Shape Zürich',
  aboutHero: 'studio-perfect-shape-zuerich-empfang',
  treatmentsHero: 'studio-perfect-shape-zuerich-behandlungsraum',
};
