// English content – keyed by the German slug. Prices (numbers) are taken from content.mjs.

const CONTRA_NOTE = 'Final suitability is assessed by a physician.';

export const EN_CATEGORIES = {
  aesthetik: { name: 'Aesthetic Medicine', short: 'Injectables, threads & regeneration' },
  laser: { name: 'Laser Treatments', short: 'Hair removal & laser skin tightening' },
  apparativ: { name: 'Device-based Skincare', short: 'Texture, pores & collagen' },
  massage: { name: 'Massages', short: 'Relaxation & body contouring' },
  peeling: { name: 'Chemical Peels', short: 'Glow & an even complexion' },
};

export const EN_TREATMENTS = {
  'fadenlifting-zuerich': {
    slug: 'thread-lift-zurich',
    name: 'PDO Threads',
    navName: 'Thread Lift (PDO Threads)',
    keyword: 'Thread lift Zurich',
    title: 'Thread Lift Zurich – PDO Threads, No Surgery | Perfect Shape',
    description: 'PDO thread lift in Zurich: a natural lift without a scalpel, results lasting 18–24 months. V-lift, jawline & double chin. Book your appointment online.',
    h1: 'Thread Lift',
    h1Accent: 'with PDO threads',
    lead: 'A natural lift without a scalpel: absorbable PDO/PLLA threads lift instantly and stimulate collagen for lasting firmness. Minimally invasive, outpatient, natural.',
    card: 'A natural lift without surgery – for cheeks, jawline & neck.',
    imageAlt: 'PDO thread lift in Zurich – vectors for a natural facial lift',
    chips: ['45–75 min.', 'Ø 18–24 months', 'Downtime 1–3 days'],
    intro: 'The thread lift is one of the most popular minimally invasive ways to tighten sagging facial contours without surgery. At Perfect Shape on Bahnhofstrasse in Zurich, every treatment is planned around your individual anatomy – from a gentle V-lift to a defined jawline or a reduced double chin.',
    what: { title: 'What is a Thread Lift?', text: 'Absorbable PDO/PLLA threads are placed through tiny entry points. Fine micro-barbs gently reposition the tissue, while the natural breakdown of the threads stimulates new collagen. The result: an immediate lifting effect combined with a lasting improvement in skin structure.', bullets: ['A natural lift without incisions or scars', 'Definition of cheeks, jawline and neck', 'Quick, outpatient, minimal downtime'] },
    indications: { title: 'Indications', items: ['Sagging jowls', 'Loss of cheek volume', 'Jawline contouring', 'Mild neck laxity', 'Double chin & under-eye bags'] },
    contra: { title: 'Contraindications', items: ['Acute skin infections', 'Pregnancy/breastfeeding', 'Blood clotting disorders', 'Unrealistic expectations'], note: CONTRA_NOTE },
    steps: [['Consultation & planning', 'Analysis, vector planning and detailed information.'], ['Local anaesthesia', 'A comfortable procedure with numbing cream or infiltration.'], ['Thread placement', 'Gently placed through micro-entry points along defined vectors.'], ['Fine-tuning & aftercare', 'Symmetry check, sterile dressing, clear recommendations.']],
    results: { title: 'Results & Longevity', items: ['Lift visible immediately, final shape after 2–4 weeks', 'Collagen production improves elasticity over months', 'Lasts 18–24 months on average'], note: '*Results vary individually.', stats: [['45–75', 'Minutes'], ['18–24', 'Months'], ['1–3', 'Days downtime']] },
    prices: [
      { name: 'Perfectshape V-Thread Lift', detail: 'Full face incl. jawline – 6 threads per side', desc: 'A complete lift for face and jawline without surgery – with long-lasting results of up to 18 months.' },
      { name: 'Firmness with Collagen Threads', detail: '40 threads', desc: 'Collagen-stimulating threads strengthen the skin structure and visibly improve elasticity within a few weeks.' },
      { name: 'Double Chin Reduction', detail: 'Combined threads & lipolysis', desc: 'Threads combined with lipolysis to effectively reduce a double chin and define the jawline.' },
      { name: 'Under-Eye Bag Reduction with Threads', detail: '5 threads per side', desc: 'Tightens and smooths the eye area for a fresher, more awake look.' },
      { name: 'Nasolabial Folds with Multi-Threads', desc: 'Gentle tightening of the nasolabial folds with special multi-threads for smoother skin.' },
      { name: 'Body Thread Lift', detail: 'Abdomen, triceps, breasts', desc: 'Thread lift for body areas – tailored to the treatment zone.', priceText: 'on request' },
    ],
    faq: [
      ['How long does a thread lift last?', 'The lifting effect usually lasts between 18 and 24 months. While the threads dissolve after a few months, the effect remains visible much longer thanks to new collagen.'],
      ['Is a thread lift painful?', 'The treatment is performed under local anaesthesia (cream or infiltration), so you usually only feel slight pressure. Most patients find it very tolerable.'],
      ['How long is the downtime?', 'Usually just 1–3 days. Mild swelling or bruising can occur and typically fades quickly.'],
      ['How much does a thread lift cost in Zurich?', 'At Perfect Shape, nasolabial fold treatment with multi-threads starts at CHF 240. The complete Perfectshape V-Thread Lift (full face incl. jawline) is CHF 1700. The final price is confirmed after your personal consultation.'],
    ],
  },
  'hyaluron-zuerich': {
    slug: 'hyaluronic-acid-fillers-zurich',
    name: 'Hyaluronic Acid',
    navName: 'Hyaluronic Acid & Lips',
    keyword: 'Fillers Zurich',
    title: 'Lip Fillers Zurich from CHF 160 | Perfect Shape',
    description: 'Hyaluronic acid fillers in Zurich: natural lip enhancement from CHF 160, nose, chin & dark circles – honest advice, no overfilling. Book online now.',
    h1: 'Hyaluronic Acid',
    h1Accent: 'volume, contour & glow',
    lead: 'Precisely placed hyaluronic fillers for natural contours, targeted volume and long-lasting hydration. Gentle, individually planned, with immediately visible results.',
    card: 'Lips, chin, nose & dark circles – natural, never overfilled.',
    imageAlt: 'Lip enhancement with hyaluronic acid in Zurich – natural lips',
    chips: ['30–45 min.', 'Ø 6–12 months', 'Minimal downtime'],
    intro: 'Whether a subtle lip enhancement, a defined chin or a fresher eye area: hyaluronic fillers are among the most versatile treatments in aesthetic medicine. In our Zurich studio we use premium brand products and give honest advice – we only recommend what truly suits your face.',
    what: { title: 'What is Hyaluronic Acid?', text: 'Hyaluronic acid is a naturally occurring molecule that binds water and gives the skin volume and elasticity. Modern HA fillers are placed in specific skin layers depending on area and goal (lips, cheeks, jawline, nasolabial folds) – for harmonious, natural results without “overfilling”.', bullets: ['Immediately visible, natural-looking results', 'Precise contouring of lips, cheeks, jawline and chin', 'Hydration boost and improved skin quality'] },
    indications: { title: 'Indications', items: ['Volume (cheeks, chin, temples)', 'Lip shape, lip volume & lip border', 'Lines: nasolabial and marionette lines', 'Dark circles & tear troughs', 'Skin hydration (skin boosters)'] },
    contra: { title: 'Contraindications', items: ['Acute inflammation/infection in the area', 'Pregnancy/breastfeeding', 'Known filler intolerance', 'Unrealistic expectations'], note: CONTRA_NOTE },
    steps: [['Consultation & analysis', 'Facial proportions, skin quality, product choice & dosage.'], ['Anaesthesia & preparation', 'Numbing cream or nerve block depending on the area, thorough disinfection.'], ['Injection & shaping', 'Tissue-friendly technique (needle/cannula), gentle moulding.'], ['Check & aftercare', 'Symmetry check, cooling, brief aftercare advice.']],
    results: { title: 'Results & Longevity', items: ['Results visible immediately, fine adjustment in the first days', 'Lasts approx. 6–12 months depending on area/product', 'Very little downtime, occasionally mild swelling'], note: '*Depends on area, skin, product and lifestyle.', stats: [['30–45', 'Minutes'], ['0–1', 'Days downtime'], ['6–12', 'Months']] },
    prices: [
      { name: 'Lip Enhancement', desc: 'Precise lip shaping with hyaluronic acid for more volume and natural contours.', priceText: 'CHF 160 (0.5 ml) · CHF 270 (1.0 ml)' },
      { name: 'Non-surgical Nose Correction', desc: 'Nose correction with fillers – fast results without downtime.' },
      { name: 'Chin / Nasolabial / Marionette Lines', detail: '1.0 ml', desc: 'Filling and shaping facial contours for a harmonious, youthful look.' },
      { name: 'Tear Trough Filler', desc: 'Gentle filling of the tear trough to reduce dark circles for a fresh look.' },
      { name: 'Expression Lines Treatment', desc: 'Treatment of expression lines (forehead, frown lines, crow’s feet) with botulinum toxin while keeping natural expression.' },
    ],
    faq: [
      ['How long does hyaluronic acid last?', 'Around 6–12 months depending on area, product and metabolism. Areas with a lot of movement (e.g. lips) usually last a little shorter.'],
      ['Is the treatment painful?', 'We work with numbing cream and/or local anaesthesia. Most patients find the injection very tolerable; a brief feeling of pressure is possible.'],
      ['What about side effects and aftercare?', 'Short-term swelling or bruising is possible. Avoid strong heat (sauna/solarium) and intense exercise for 24 hours and cool the area if needed.'],
      ['How much do lip fillers cost in Zurich?', 'At Perfect Shape, lip enhancement with hyaluronic acid costs CHF 160 for 0.5 ml and CHF 270 for 1.0 ml. We advise you honestly on how much makes sense.'],
    ],
  },
  'mesotherapie-zuerich': {
    slug: 'mesotherapy-zurich',
    name: 'Mesotherapy',
    navName: 'Mesotherapy',
    keyword: 'Mesotherapy Zurich',
    title: 'Mesotherapy Zurich – Glow, Hair & Dark Circles | Perfect Shape',
    description: 'Mesotherapy in Zurich for glow, hair growth, dark circles & cellulite. Individual active-ingredient cocktails from CHF 130 – book your appointment online.',
    h1: 'Mesotherapy',
    h1Accent: 'a boost for glow & vitality',
    lead: 'Gentle micro-injections of tailored active-ingredient cocktails (vitamins, amino acids, hyaluronic acid) boost circulation, regeneration and hydration – for visibly fresher, finer skin.',
    card: 'Tailored active cocktails for skin, hair & the eye area.',
    imageAlt: 'Facial mesotherapy in Zurich – micro-injections for fresh skin',
    chips: ['30–45 min.', 'Course: 3–6 sessions', 'Every 2–4 weeks'],
    intro: 'Mesotherapy is the classic choice for an intense freshness boost – or to target hair loss, dark circles and cellulite. At Perfect Shape in Zurich, we tailor the active-ingredient cocktail to your individual goal.',
    what: { title: 'What is Mesotherapy?', text: 'Mesotherapy combines very fine micro-injections with individually tailored active-ingredient blends. Vitamins, antioxidants, peptides and non-cross-linked hyaluronic acid are delivered exactly where they work – into the superficial skin layers.', bullets: ['Better hydration & skin quality (“glow”)', 'Finer pores, a more even complexion', 'Stimulates metabolism & regeneration'] },
    indications: { title: 'Indications', items: ['Fatigue & dryness lines', 'Dull complexion, loss of glow', 'Fine pores & skin texture', 'Neck, décolleté, hands', 'Hair loss & thinning hair'] },
    contra: { title: 'Contraindications', items: ['Acute inflammation/infection in the area', 'Pregnancy/breastfeeding', 'Known intolerance to ingredients', 'Blood clotting disorders'], note: CONTRA_NOTE },
    steps: [['Consultation & formula', 'Analysis of skin and goals, choice of the active cocktail.'], ['Preparation', 'Cleansing, numbing cream if needed, careful disinfection.'], ['Micro-injections', 'Tiny deposits in the upper dermis (manual or with a meso gun).'], ['Finish & care', 'Cooling, skincare advice, course planning.']],
    results: { title: 'Results & Longevity', items: ['Fresher, plumper complexion often after the first session', 'Clear improvement in texture after a course (3–6 sessions)', 'Maintain with a refresher every 3–6 months'], note: '*Depending on skin, area and skincare routine.', stats: [['30–45', 'Minutes'], ['3–6', 'Sessions (course)'], ['3–6', 'Months maintenance']] },
    prices: [
      { name: 'Hair Follicle Mesotherapy', desc: 'Stimulates the hair follicles, strengthens the hair structure and promotes natural hair growth.', extra: '4-session course – CHF 700' },
      { name: '“Like a BTX” Mesotherapy', desc: 'A smoothing effect without botulinum toxin – for firmer, finer-looking skin.' },
      { name: '“Cellu Killer” Mesotherapy', desc: 'Special treatment to reduce cellulite and improve skin firmness in problem areas.' },
      { name: 'Dark Circles Mesotherapy', desc: 'Hydrating and brightening treatment for the delicate eye area.' },
    ],
    faq: [
      ['How many sessions are recommended?', 'For visible, stable results we recommend a course of 3–6 sessions every 2–4 weeks. Refreshers every 3–6 months maintain the effect.'],
      ['Does mesotherapy hurt?', 'With numbing cream and very fine needles the treatment is generally well tolerated. Brief stinging is possible and fades quickly.'],
      ['Are there side effects?', 'Temporary redness, small bumps or pinpoint bruises are possible and usually disappear within a few days. Please avoid sauna/solarium and intense exercise for 24 hours.'],
      ['Does mesotherapy help with hair loss?', 'Yes – hair follicle mesotherapy specifically stimulates the scalp and can promote natural hair growth. We recommend a course of 4 sessions (CHF 700).'],
    ],
  },
  'biostimulatoren-zuerich': {
    slug: 'biostimulators-zurich',
    name: 'Biostimulators',
    navName: 'Biostimulators',
    keyword: 'Biostimulators Zurich',
    title: 'Biostimulators Zurich – Natural Collagen Boost | Perfect Shape',
    description: 'Biostimulators in Zurich: polynucleotides & PLLA liquid facelift for natural collagen production, lasting 12–24 months. From CHF 350 – book online.',
    h1: 'Biostimulators',
    h1Accent: 'collagen from within',
    lead: 'Biostimulators activate your body’s own collagen production – for firmer contours, better skin quality and very natural, gradually increasing results that last.',
    card: 'Polynucleotides & PLLA – natural firming with your own collagen.',
    imageAlt: 'Biostimulator treatment in Zurich – facial collagen boost',
    chips: ['30–50 min.', 'Build-up 6–12 weeks', 'Lasts 12–24 months'],
    intro: 'Biostimulators such as polynucleotides or poly-L-lactic acid (PLLA) are the modern answer to declining firmness: instead of simply “filling”, they stimulate your skin to produce collagen again. The result develops gently over weeks – and looks especially natural.',
    what: { title: 'What are Biostimulators?', text: 'Biostimulators (e.g. poly-L-lactic acid, polynucleotides) specifically stimulate new collagen in the skin. Unlike classic fillers, which provide volume mainly through the injected material, the effect comes from your own tissue response – denser, more elastic tissue and natural-looking firming.', bullets: ['A very natural, gradual increase in effect', 'Improved density, elasticity & texture', 'Long-lasting thanks to your own collagen'] },
    indications: { title: 'Indications', items: ['Mild to moderate loss of volume & structure', 'Cheeks, jawline, chin, temples', 'Skin laxity, contour definition', 'Skin quality: pores & elasticity'] },
    contra: { title: 'Contraindications', items: ['Acute inflammation/infection in the area', 'Pregnancy/breastfeeding', 'Active autoimmune disease, tendency to keloids', 'Intolerance to ingredients'], note: CONTRA_NOTE },
    steps: [['Consultation & planning', 'Analysis of anatomy & skin quality, choice of biostimulator.'], ['Preparation', 'Cleansing, numbing cream if needed, sterile disinfection.'], ['Injection', 'Gentle technique (needle/cannula) for an even build-up.'], ['Build-up & check', 'The effect develops over weeks; check-up after 8–12 weeks.']],
    results: { title: 'Results & Longevity', items: ['First changes after a few weeks, peak after 2–3 months', 'Typically lasts 12–24 months (product & area dependent)', 'Very natural remodelling – no “overfilled” look'], note: '*Depending on area, product, lifestyle and individual tissue response.', stats: [['30–50', 'Minutes'], ['6–12', 'Weeks build-up'], ['12–24', 'Months']] },
    prices: [
      { name: 'Liquid Facelift with PLLA Biostimulators', detail: '10 ml', desc: 'Comprehensive facial rejuvenation with biostimulators – no scalpel needed.' },
      { name: 'Skin Revitalisation with Polynucleotides', desc: 'Minimally invasive injection therapy with polynucleotides (DNA fragments) that boosts natural cell regeneration and collagen production.' },
    ],
    faq: [
      ['How do biostimulators differ from fillers?', 'Fillers add volume mainly through the material itself. Biostimulators stimulate your own collagen – the effect grows over weeks, looks very natural and usually lasts longer.'],
      ['How many sessions do I need?', 'Depending on your starting point, 1–3 sessions are typical. We check the build-up after 8–12 weeks and add more if needed.'],
      ['Is there downtime?', 'Usually minimal. Short-term redness, swelling or small bruises are possible. Avoid strong heat and intense exercise for 24 hours.'],
    ],
  },
  'prp-vampirelifting-zuerich': {
    slug: 'prp-vampire-facelift-zurich',
    name: 'PRP Vampire Facelift',
    navName: 'PRP Vampire Facelift',
    keyword: 'PRP Zurich',
    title: 'PRP Vampire Facelift Zurich – Skin & Hair | Perfect Shape',
    description: 'PRP vampire facelift in Zurich: your own plasma for glow, finer skin & against hair loss. 100% natural. From CHF 300 – book your appointment online.',
    h1: 'PRP Vampire Facelift',
    h1Accent: 'with your own plasma',
    lead: 'Concentrated platelet-rich plasma (PRP) obtained from your own blood stimulates natural regeneration: more glow, finer texture, more elastic skin – completely natural and without foreign substances.',
    card: 'Your own plasma for glow, elasticity & stronger hair.',
    imageAlt: 'PRP vampire facelift in Zurich – treatment for face and scalp',
    chips: ['45–60 min.', 'Course: 3 sessions', 'Every 4–6 weeks'],
    intro: 'The PRP vampire facelift uses your body’s own regenerative power. It is ideal for anyone looking for natural skin rejuvenation without fillers – and a proven option for hair loss.',
    what: { title: 'What is a PRP Vampire Facelift?', text: 'Your own plasma, rich in growth factors, is obtained from a small blood sample. This PRP is injected into the target areas or worked in with microneedling. The result: stimulated cell regeneration, new collagen and improved skin density – 100% natural.', bullets: ['Natural biostimulation without foreign material', 'More glow, elasticity and fewer fine lines', 'Also for neck, décolleté, hands or scalp'] },
    indications: { title: 'Indications', items: ['Tired complexion, loss of elasticity', 'Fine lines (e.g. around eyes/lips)', 'Texture & pores, fine scars', 'Hair loss, thinning hair'] },
    contra: { title: 'Contraindications', items: ['Acute infection/inflammation in the area', 'Clotting disorders, anticoagulation', 'Pregnancy/breastfeeding', 'Severe autoimmune disease'], note: CONTRA_NOTE },
    steps: [['Blood draw & preparation', 'Gentle blood draw, centrifugation to obtain the PRP.'], ['Optional numbing', 'Numbing cream depending on the area, thorough disinfection.'], ['Application', 'Targeted or area injections, or microneedling.'], ['Aftercare & course plan', 'Cooling, skincare, sun protection; planning the series.']],
    results: { title: 'Results & Longevity', items: ['First changes after 2–4 weeks, peak after 2–3 months', 'Typically lasts 9–18 months', 'Very natural remodelling through your own growth factors'], note: '*Varies by area, skin condition, lifestyle and number of sessions.', stats: [['45–60', 'Minutes'], ['3', 'Sessions (course)'], ['9–18', 'Months']] },
    prices: [
      { name: 'PRP – Face', desc: 'Plasma treatment for skin rejuvenation and natural regeneration.' },
      { name: 'PRP – Scalp', desc: 'Strengthens hair roots, reduces hair loss and promotes hair growth.' },
    ],
    faq: [
      ['How many sessions do I need?', 'For stable results we recommend a course of 3 sessions every 4–6 weeks. A refresher 1–2× a year helps maintain the result.'],
      ['Is there downtime?', 'Usually only mild redness or swelling for 1–2 days. Please avoid strong heat and intense exercise for 24 hours and use sun protection.'],
      ['Is PRP safe?', 'PRP is autologous (from your own body) – the risk of allergic reactions is very low. We clarify contraindications during the consultation.'],
    ],
  },
  'laser-haarentfernung-zuerich': {
    slug: 'laser-hair-removal-zurich',
    name: 'Permanent Hair Removal',
    navName: 'Laser Hair Removal',
    keyword: 'Laser hair removal Zurich',
    title: 'Laser Hair Removal Zurich from CHF 40 | Perfect Shape',
    description: 'Permanent laser hair removal (diode/SHR) in Zurich: upper lip CHF 40, underarms CHF 80, full body CHF 400. Certified laser safety – book online.',
    h1: 'Laser Hair Removal',
    h1Accent: 'permanently smooth skin',
    lead: 'Efficient, skin-friendly reduction of unwanted hair with professional laser/SHR technology. For lasting smooth skin on the face, underarms, bikini area, legs and more.',
    card: 'Diode laser/SHR for permanently smooth skin – face to full body.',
    imageAlt: 'Permanent laser hair removal on the legs in Zurich',
    chips: ['15–60 min.', '6–8 sessions', 'Diode laser/SHR'],
    intro: 'Never shave, wax or pluck again: with permanent hair removal using a diode laser or SHR technology, we reduce unwanted hair growth for good – gently, safely and with transparent prices per zone. Treatments are performed by a certified laser safety officer.',
    what: { title: 'How does Laser Hair Removal work?', text: 'Laser/SHR pulses specifically heat and deactivate the hair root (follicle). As hair grows in cycles, several sessions are needed to reach the follicles in their growth phase. The result: significantly less hair growth up to long-term smooth skin.', bullets: ['Safe & precise – targeted at the follicles', 'Gentle on the skin thanks to controlled energy', 'Lasting reduction of hair growth'] },
    indications: { title: 'Treatment Areas', items: ['Face (upper lip, chin)', 'Underarms, arms', 'Bikini/intimate area', 'Legs, back, chest, abdomen'] },
    contra: { title: 'Your Benefits', items: ['Saves time: no more shaving/waxing', 'Fewer ingrown hairs & irritation', 'Even, smooth skin'], note: 'Effectiveness depends on hair colour, density, skin type and hormones.', positive: true },
    steps: [['Consultation & test', 'Skin/hair analysis, information and a test pulse if needed.'], ['Preparation', 'Shaved areas, clean and dry skin; protective glasses.'], ['Laser treatment', 'Targeted pulses across the area; cooling for comfort.'], ['Aftercare', 'Cooling, gentle care, UV protection; next session after 4–8 weeks.']],
    results: { title: 'Results & Longevity', items: ['Hair reduction visible after just a few sessions', 'Lasting effect after a series of 6–8 sessions', 'A maintenance session 1–2× a year may be useful'], note: '*Individual, depending on hair colour/thickness, skin type, area and hormones.', stats: [['15–60', 'Minutes / session'], ['6–8', 'Sessions (series)'], ['4–8', 'Weeks apart']] },
    prices: [
      { name: 'Upper Lip / Chin', desc: 'Effective hair removal for small facial areas for long-lasting smoothness.' },
      { name: 'Underarms / Bikini Line', desc: 'Gentle and thorough laser hair removal for lasting results.' },
      { name: 'Bikini Front', desc: 'Precise hair removal in the front bikini area.' },
      { name: 'Full Bikini + Buttock Crease', desc: 'Complete hair removal in the intimate area for smooth skin without shaving.' },
      { name: 'Lower Legs / Arms', desc: 'Lasting hair-free legs or arms.' },
      { name: 'Back / Chest & Abdomen', desc: 'Efficient treatment of large areas for smooth skin.' },
      { name: 'Full Legs', desc: 'Complete treatment of both legs for permanently smooth results.' },
      { name: 'Full Body', desc: 'Full-body laser treatment for completely hair-free skin.' },
    ],
    priceNote: 'Ask about our value packages for optimal results at an attractive price.',
    faq: [
      ['How many sessions do I need?', 'Usually 6–8 sessions every 4–8 weeks; this may vary depending on area, skin/hair and goals.'],
      ['Does laser hair removal hurt?', 'Most people find it very tolerable. Cooling significantly reduces the warm or prickling sensation.'],
      ['What should I consider before and after?', 'Avoid strong heat (sauna/solarium) and intense exercise for 24–48 hours and use sun protection. Between sessions please only shave – do not wax or pluck.'],
      ['Who is it suitable for?', 'Many skin types benefit. Very light, fine or grey hair responds less well. We check suitability and adjust parameters individually during the consultation.'],
      ['How much does laser hair removal cost in Zurich?', 'At Perfect Shape a session starts at CHF 40 (upper lip/chin), underarms CHF 80, full legs CHF 200 and full body CHF 400.'],
    ],
  },
  'endolift-zuerich': {
    slug: 'endolift-zurich',
    name: 'Endolift®',
    navName: 'Endolift®',
    keyword: 'Endolift Zurich',
    title: 'Endolift® Zurich – Laser Skin Tightening | Perfect Shape',
    description: 'Endolift® in Zurich: minimally invasive laser tightening for neck, jawline, double chin & knees – no incisions, no scars. CHF 1800 per zone. Book online.',
    h1: 'Endolift®',
    h1Accent: 'tightening without surgery',
    lead: 'A minimally invasive laser treatment to tighten skin, define contours and improve skin quality. Ideal for the neck, jawline/double chin and body areas such as the knees – no incisions, no scars.',
    card: 'Laser-fibre tightening for neck, jawline, double chin & knees.',
    imageAlt: 'Endolift® laser treatment on neck and jawline in Zurich',
    chips: ['approx. 45–60 min.', 'Minimally invasive', 'Short downtime'],
    intro: 'Endolift® is one of the most innovative methods of skin tightening without a scalpel. A hair-thin laser fibre works directly beneath the skin – tightening tissue, defining contours and, depending on the zone, reducing small fat deposits. At Perfect Shape in Zurich we work with the original Endolift® system.',
    what: { title: 'What is Endolift®?', text: 'Endolift® is a minimally invasive laser treatment for skin tightening and contour improvement. An ultra-thin laser fibre delivers energy precisely into the tissue – to stimulate collagen and (depending on the zone) reduce small fat deposits.', bullets: ['No incisions, no scars', 'Targeted tightening & contour definition', 'Improved skin structure and firmness'] },
    indications: { title: 'Treatment Areas', items: ['Neck', 'Jawline & double chin', 'Knees'] },
    contra: { title: 'Your Benefits', items: ['Minimally invasive – no surgical facelift', 'Short recovery time', 'Natural-looking tightening through new collagen'], note: 'A personal consultation clarifies realistic goals and the ideal zone.', positive: true },
    steps: [['Consultation & planning', 'Analysis of the zone, information, defining the goal.'], ['Treatment', 'Precise laser energy via a fine fibre – tightening and contouring.'], ['Aftercare', 'Mild swelling/redness possible – short downtime depending on the zone.']],
    results: { title: 'Results', items: ['Initial tightening often visible soon', 'Further improvement over weeks through collagen', 'More defined contours and better skin quality'], note: '*Results are individual and depend on the initial situation and lifestyle.', stats: [['45–60', 'Minutes'], ['1', 'Zone per session'], ['0', 'Incisions & scars']] },
    prices: [
      { name: '1 Zone – Jawline & Double Chin', desc: 'Contouring of the jawline and reduction of the double chin for a more defined profile.' },
      { name: '1 Zone – Neck', desc: 'Tightening of the neck skin and improved texture with a minimally invasive laser fibre.' },
      { name: '1 Zone – Knees', desc: 'Skin tightening around the knees for smoother skin and better tissue tension.' },
    ],
    priceNote: 'We recommend a personal consultation to define the ideal zone and goal.',
    faq: [
      ['Is Endolift® painful?', 'The treatment is generally well tolerated. Sensations such as warmth or slight pulling are possible. We discuss details in the consultation.'],
      ['How long is the recovery time?', 'Most people are socially presentable again quickly. Mild swelling or redness may occur briefly – depending on the zone and individual reaction.'],
      ['When will I see results?', 'An initial tightening effect can be visible soon. Further improvement develops over several weeks as collagen production is stimulated.'],
      ['Who is Endolift® suitable for?', 'For anyone who wants tightening or contouring without surgery. We assess suitability, expectations and contraindications individually.'],
    ],
  },
  'rf-needling-zuerich': {
    slug: 'rf-microneedling-zurich',
    name: 'RF Microneedling',
    navName: 'RF Microneedling',
    keyword: 'RF microneedling Zurich',
    title: 'RF Microneedling Zurich – Acne Scars & Pores | Perfect Shape',
    description: 'RF microneedling in Zurich for acne scars, enlarged pores & fine lines. Face + neck CHF 230, course of 4 CHF 850. Short downtime – book online now.',
    h1: 'RF Microneedling',
    h1Accent: 'collagen boost & tightening',
    lead: 'Combines microneedling with radiofrequency to heat the dermis in a targeted way, stimulate collagen and refine skin texture – effective for pores, acne scars and fine lines, with short downtime.',
    card: 'Radiofrequency microneedling for scars, pores & fine lines.',
    imageAlt: 'RF microneedling facial treatment in Zurich',
    chips: ['45–60 min.', 'Course: 3–4 sessions', 'Every 4–6 weeks'],
    intro: 'RF microneedling is one of the most effective device-based treatments for visibly refined skin. The combination of microneedling and radiofrequency works deep – ideal for acne scars, enlarged pores and early skin laxity.',
    what: { title: 'What is RF Microneedling?', text: 'RF microneedling uses fine, gold-plated needles that deliver short radiofrequency pulses into the dermis. This creates controlled micro-channels and thermal stimulation that boost your own collagen and elastin – for firmer, smoother skin without adding volume.', bullets: ['Improves pores, texture & fine lines', 'Reduces acne scars & mild stretch marks', 'Tightens cheeks, jawline and neck'] },
    indications: { title: 'Indications', items: ['Enlarged pores, uneven texture', 'Acne scars (atrophic), post-acne', 'Fine lines, mild skin laxity', 'Neck, décolleté, upper lip area'] },
    contra: { title: 'Contraindications', items: ['Acute inflammation/infection in the area', 'Pregnancy/breastfeeding', 'Isotretinoin therapy (< 6 months)', 'Metal implants in the area, active herpes'], note: CONTRA_NOTE },
    steps: [['Consultation & planning', 'Indication check, areas, depth & RF parameters, number of sessions.'], ['Preparation', 'Cleansing, numbing cream, disinfection.'], ['RF microneedling', 'Fractional treatment with RF delivery at a defined depth.'], ['Finish & aftercare', 'Soothing care, sun protection (SPF 50), avoid sport/sauna for 24–48 h.']],
    results: { title: 'Results & Longevity', items: ['Instant effect: plumper, smoother complexion', 'Structural build-up (collagen/elastin) over 6–12 weeks', 'A course of 3–4 sessions is recommended'], note: '*Mild redness possible for 0–24 h; make-up usually the next day.', stats: [['45–60', 'Minutes'], ['3–4', 'Sessions (course)'], ['6–12', 'Weeks collagen build-up']] },
    prices: [
      { name: 'RF Microneedling Course (4×)', desc: 'Intensive course with a lasting lifting and regenerating effect.' },
      { name: 'RF Microneedling Face + Neck', desc: 'Microneedling combined with radiofrequency for skin tightening and improved texture.' },
    ],
    faq: [
      ['How many sessions do I need?', 'We usually recommend a course of 3–4 sessions every 4–6 weeks. Refreshers after 6–12 months keep the effect stable.'],
      ['Is the treatment painful?', 'Thanks to numbing cream, RF microneedling is well tolerated. Right afterwards the skin may feel warm or tingly and be slightly red for 1–3 days.'],
      ['What is important afterwards?', 'Avoid sport and heat for 24–48 hours, use gentle care and SPF 50 daily. Only resume retinoids and acids once the skin has calmed down.'],
    ],
  },
  'microdermabrasion-zuerich': {
    slug: 'microdermabrasion-zurich',
    name: 'Microdermabrasion',
    navName: 'Microdermabrasion',
    keyword: 'Microdermabrasion Zurich',
    title: 'Microdermabrasion Zurich – Glow & Pores | Perfect Shape',
    description: 'Microdermabrasion in Zurich: gentle deep cleansing for finer pores and an instant glow – no downtime. CHF 145 per treatment. Book your appointment online.',
    h1: 'Microdermabrasion',
    h1Accent: 'instant glow & fine pores',
    lead: 'Gentle, controlled removal of the top layer of skin with fine crystals or diamond tips. Stimulates cell renewal, smooths the surface and improves the absorption of active ingredients.',
    card: 'Deep cleansing for finer pores & an instant glow.',
    imageAlt: 'Microdermabrasion facial deep cleansing in Zurich',
    chips: ['30–45 min.', 'Course: 3–6 sessions', 'No downtime'],
    intro: 'Microdermabrasion is the perfect treatment for a fresh, even complexion – before a special occasion or as a regular skincare course. Gentle, without downtime and with immediately visible results.',
    what: { title: 'What is Microdermabrasion?', text: 'Microdermabrasion evenly removes the outermost layer of skin (stratum corneum). This refines the texture, reduces roughness and supports cell regeneration. Combined with nourishing serums, the results can be enhanced even further.', bullets: ['Instant glow & smoother skin', 'Finer pores, a more even complexion', 'Better absorption of active ingredients'] },
    indications: { title: 'Indications', items: ['Tired, dull complexion', 'Uneven texture, rough patches', 'Enlarged/clogged pores', 'Fine lines, dryness lines'] },
    contra: { title: 'Contraindications', items: ['Active acne/inflammation, herpes', 'Eczema, rosacea flare-ups, fresh wounds', 'Isotretinoin therapy (< 6 months)', 'Intolerance to the products used'], note: 'Suitability is checked individually on site.' },
    steps: [['Consultation & skin analysis', 'Defining skin condition, goals, intensity and serums.'], ['Preparation', 'Cleansing & disinfection, enzyme peel if needed.'], ['Microdermabrasion', 'Even exfoliation adapted to area & sensitivity.'], ['Soothing & protection', 'Serums, hydration, finishing care & SPF 50.']],
    results: { title: 'Results & Longevity', items: ['Instantly fresher, more even complexion', 'Refined pores & better absorption of actives', 'For lasting results: a course of 3–6 sessions'], note: '*Brief redness possible; usually ready for everyday life immediately.', stats: [['30–45', 'Minutes'], ['3–6', 'Sessions (course)'], ['0', 'Days downtime']] },
    prices: [
      { name: 'Microdermabrasion (Deep Cleansing)', desc: 'A gentle, deep-cleansing peel for an even, fresh complexion.' },
    ],
    faq: [
      ['Which skin types is it suitable for?', 'Most skin types – especially rough texture, clogged pores and dull skin. Not suitable for active inflammation, herpes, eczema or acute rosacea.'],
      ['Is there downtime?', 'Usually none. Brief redness or sensitivity is possible. Avoid sport, sauna and strong sun for 24 hours; use SPF 50 daily.'],
      ['Can it be combined with other treatments?', 'Yes. Popular combinations are mesotherapy or a chemical peel. We are happy to advise on the right order and intervals.'],
    ],
  },
  'carbon-laser-peeling-zuerich': {
    slug: 'carbon-laser-peel-zurich',
    name: 'Carbon Laser Peel',
    navName: 'Carbon Laser Peel',
    keyword: 'Carbon laser peel Zurich',
    title: 'Carbon Laser Peel Zurich – Hollywood Peel | Perfect Shape',
    description: 'Carbon laser peel (“Hollywood Peel”) in Zurich: refined pores, clear skin & an instant glow without downtime. Face from CHF 200. Book online now.',
    h1: 'Carbon Laser Peel',
    h1Accent: 'the Hollywood Peel',
    lead: 'A carbon lotion binds sebum and dead skin cells, then the laser gently vaporises the layer: pores are cleansed and texture refined – for an instant glow. Ideal for combination skin and enlarged pores.',
    card: 'The “Hollywood Peel” for refined, clear skin.',
    imageAlt: 'Carbon laser peel – Hollywood Peel treatment in Zurich',
    chips: ['30–45 min.', 'Course: 3–5 sessions', 'Downtime 0–1 day'],
    intro: 'The carbon laser peel – known as the “Hollywood Peel” – is the ideal treatment before special occasions. It refines pores, mattifies the skin and leaves a radiant, clear complexion with practically no downtime.',
    what: { title: 'What is a Carbon Laser Peel?', text: 'A fine carbon lotion is applied, which binds to sebum, dead skin cells and impurities. A Q-switched laser then precisely vaporises this layer, cleanses the pores and stimulates skin renewal at the same time.', bullets: ['Instant glow & refined-looking pores', 'Mattified, smoother texture, fewer blackheads', 'Gentle, hardly any downtime'] },
    indications: { title: 'Indications', items: ['Enlarged pores, oily T-zone', 'Uneven/rough texture, blackheads', 'Post-acne marks, pigmentation', 'Refreshing the complexion before events'] },
    contra: { title: 'Contraindications', items: ['Active inflammation/herpes in the area', 'Fresh sunburn, recent strong peel', 'Isotretinoin therapy (< 6 months)', 'Pregnancy/breastfeeding (individual)'], note: 'Suitability is assessed individually on site.' },
    steps: [['Consultation & selection', 'Skin analysis, indication check and parameters.'], ['Cleansing & carbon lotion', 'Gentle cleansing, application of the carbon suspension.'], ['Laser pass', 'The laser selectively vaporises the carbon layer and clears the pores.'], ['Soothing & protection', 'Cooling, hydration, serums if needed and SPF 50.']],
    results: { title: 'Results & Longevity', items: ['Instant effect: matte, clearer, finer-looking skin', 'Reduces sebum & refines pores over several weeks', 'Recommended: 3–5 sessions every 2–4 weeks'], note: '*Minimal downtime (0–1 day); mild redness possible.', stats: [['30–45', 'Minutes'], ['3–5', 'Sessions (course)'], ['0–1', 'Days downtime']] },
    prices: [
      { name: 'Face', desc: 'Refines pores, reduces pigmentation and stimulates collagen production.' },
      { name: 'Face & Neck', desc: 'Effective skin refresh for face and neck in one session.' },
      { name: 'Hands', desc: 'Brightening and smoothing of the skin on the hands for a more even look.' },
    ],
    faq: [
      ['Is there downtime?', 'Usually none. Brief redness is possible. Avoid strong sun, sauna and intense exercise for 24 hours; use SPF 50 daily.'],
      ['Who is the carbon peel particularly suitable for?', 'Ideal for combination skin, enlarged pores, blackheads and a dull complexion. With acute inflammation, herpes or fresh sunburn we advise waiting.'],
      ['Can it be combined with other treatments?', 'Yes – e.g. with microdermabrasion or light acid peels. We advise on the right order and intervals.'],
    ],
  },
  'klassische-massage-zuerich': {
    slug: 'massage-zurich',
    name: 'Classic Massage',
    navName: 'Classic Massage',
    keyword: 'Massage Zurich',
    title: 'Massage Zurich – Classic & Lymphatic | Perfect Shape',
    description: 'Classic massage & lymphatic drainage in Zurich on Bahnhofstrasse: relieves tension and reduces stress. 55 min. CHF 120. Book your massage online now.',
    h1: 'Classic Massage',
    h1Accent: 'relaxation & release',
    lead: 'Partial or full-body classic massage to release muscle tension, boost circulation and calm the nervous system. Ideal for neck/back complaints, stress and fatigue.',
    card: 'Releases tension, reduces stress – incl. lymphatic drainage.',
    imageAlt: 'Classic back massage in Zurich – relaxation at Perfect Shape',
    chips: ['55 min.', 'Single or as a course', 'No downtime'],
    intro: 'A break in the heart of Zurich: our classic massage releases tension in the neck, shoulders and back and gives you noticeable new energy – perfect after a long working day or intense training. We massage with expertise in sports science and lymphatic drainage.',
    what: { title: 'What is a Classic Massage?', text: 'The classic (Swedish) massage uses strokes, kneading, friction and stretching. It releases muscular tension, improves microcirculation and supports regeneration and stress relief – as a partial or full-body treatment.', bullets: ['Releases tension & improves mobility', 'Boosts circulation & metabolism', 'Less stress, better sleep & well-being'] },
    indications: { title: 'Indications', items: ['Neck, shoulder & back tension', 'Desk work, screen time', 'Muscle overload after sport', 'Stress, restlessness'] },
    contra: { title: 'Contraindications', items: ['Acute inflammation, fever, infections', 'Fresh injuries/surgery, acute thrombosis', 'Open skin lesions, severe bruising', 'Unexplained pain – consult a doctor first'], note: 'Suitability & intensity are determined individually on site.' },
    steps: [['Questions & goals', 'Brief questions about complaints, preferred intensity and focus areas.'], ['Preparation', 'Comfortable positioning, aromatic massage oil on request.'], ['Massage', 'Classic sequence of techniques, pressure adjusted continuously.'], ['Rest & tips', 'Short rest, hydration advice, tips for home.']],
    results: { title: 'Results & Effects', items: ['Instantly noticeable relaxation & better circulation', 'Releases muscle tension & reduces stress', 'For lasting effects: regularly (weekly/fortnightly)'], note: '*No downtime; adapted to individual needs.', stats: [['55', 'Minutes'], ['1×', 'per week for complaints'], ['0', 'Days downtime']] },
    prices: [
      { name: 'Classic Massage', detail: '55 min.', desc: 'Relaxing full-body massage to loosen muscles and reduce stress.' },
      { name: 'Lymphatic Drainage', desc: 'A gentle manual technique to support lymph flow and decongest tissue.' },
    ],
    faq: [
      ['Does a classic massage hurt?', 'It may be “pleasantly intense”, but never painful. We adjust the pressure at any time – just give us feedback.'],
      ['Is there downtime?', 'Usually not. Mild tiredness or muscle soreness may occur – drink plenty of water, moderate movement is recommended.'],
      ['How often should I come?', 'For acute tension 1× a week for 3–4 weeks. For maintenance every 2–4 weeks or as needed.'],
    ],
  },
  'anti-cellulite-massage-zuerich': {
    slug: 'anti-cellulite-massage-zurich',
    name: 'Anti-Cellulite Massage',
    navName: 'Anti-Cellulite & Maderotherapy',
    keyword: 'Anti-cellulite massage Zurich',
    title: 'Anti-Cellulite Massage & Maderotherapy Zurich | Perfect Shape',
    description: 'Anti-cellulite massage & maderotherapy in Zurich for smoother skin on legs & buttocks. From CHF 120, 10-session package CHF 1350. Book online now.',
    h1: 'Anti-Cellulite Massage',
    h1Accent: 'smoother contours',
    lead: 'Special techniques, rhythmic kneading and drainage strokes stimulate microcirculation, support lymph flow and loosen adhesions – for visibly smoother skin on thighs and buttocks.',
    card: 'Massage & maderotherapy for smoother legs & buttocks.',
    imageAlt: 'Anti-cellulite leg massage in Zurich',
    chips: ['45–55 min.', 'Course: 6–10 sessions', '1–2× per week'],
    intro: 'Cellulite is not a flaw – but many women wish for smoother, firmer skin. Our anti-cellulite massage and maderotherapy (wood therapy) target exactly that. Agnieszka Jaggy is a nutritionist specialising in cellulite and also supports you with tips for everyday life.',
    what: { title: 'What is an Anti-Cellulite Massage?', text: 'The anti-cellulite massage combines deep kneading, shearing and rolling techniques with drainage-oriented strokes. The goal is to boost microcirculation, reduce water retention and improve tissue firmness. Cupping or wooden tools (maderotherapy) can be used optionally.', bullets: ['Boosts lymph flow & circulation', 'Loosens adhesions & improves the skin', 'Supports contours & well-being'] },
    indications: { title: 'Indications', items: ['Orange-peel skin on thighs, buttocks, hips', 'Heavy legs, water retention', 'Declining tissue firmness', 'As a complement to sport & a balanced diet'] },
    contra: { title: 'Contraindications', items: ['Acute inflammation, fever, infections', 'Varicose veins/thrombosis, vascular disease', 'Recent surgery/injuries, bruising tendency', 'Pregnancy – only after consultation'], note: 'Suitability & intensity are determined individually on site.' },
    steps: [['Analysis & goals', 'Check of the areas & agreement on intensity and course plan.'], ['Preparation', 'Comfortable positioning; optional warming gel/oil.'], ['Treatment', 'Kneading, shearing and rolling techniques, lymphatic drainage; optional wooden tools.'], ['Aftercare & course', 'Course plan, hydration advice, exercise and self-massage tips.']],
    results: { title: 'Results & Progress', items: ['Improves microcirculation & lymph flow', 'Smoother-looking skin with regular treatment', 'Course: 6–10 sessions, then maintenance'], note: '*Exercise & sufficient hydration support the result.', stats: [['45–55', 'Minutes'], ['6–10', 'Sessions (course)'], ['1–2×', 'per week']] },
    prices: [
      { name: '10-Session Anti-Cellulite Package', desc: 'An intensive course for visible, long-lasting results.' },
      { name: 'Anti-Cellulite Massage', detail: '55 min.', desc: 'A firming massage to reduce cellulite and improve skin texture.' },
      { name: 'Maderotherapy', detail: '45 min.', desc: 'Special wood therapy to stimulate metabolism and smooth the skin.' },
    ],
    faq: [
      ['Is the treatment painful?', 'The massage is firm but should be well tolerated. We adjust the intensity individually with you.'],
      ['Do I need a course?', 'Single sessions are possible. For visible and stable results we recommend a course of 6–10 sessions, 1–2× a week – e.g. with our 10-session package.'],
      ['What can I do myself?', 'Regular exercise, a balanced diet, drinking enough water and a short daily self-massage support the result sustainably.'],
    ],
  },
  'fruchtsaeure-peeling-zuerich': {
    slug: 'chemical-peel-zurich',
    name: 'Fruit Acid Peel',
    navName: 'Chemical Peel & PRX-T33',
    keyword: 'Chemical peel Zurich',
    title: 'Chemical Peel Zurich – PRX-T33 Peel | Perfect Shape',
    description: 'Fruit acid treatment & PRX-T33 peel in Zurich: an even complexion, fine pores and glow – without peeling. CHF 180. Book your appointment online now.',
    h1: 'Chemical Peel',
    h1Accent: 'an even complexion',
    lead: 'Controlled AHA/BHA peels gently dissolve dead skin cells, promote renewal and leave the complexion fresher, smoother and more even – ideal for dull skin, fine lines and impurities.',
    card: 'AHA/BHA & PRX-T33 – glow without peeling.',
    imageAlt: 'Chemical facial peel in Zurich – PRX-T33 treatment',
    chips: ['30–45 min.', 'Course: 3–6 sessions', 'Every 2–4 weeks'],
    intro: 'A professional fruit acid peel is the fastest way to a clearer, more radiant complexion. Our PRX-T33 peel is especially popular: it intensively biorevitalises the skin – without visible peeling.',
    what: { title: 'What is a Chemical Peel?', text: 'In a fruit acid treatment (AHA/BHA peel), mild to medium acids (e.g. glycolic, lactic, mandelic or salicylic acid) are applied for a controlled time depending on skin type. This dissolves dead cells, refines pores and promotes an even complexion. Concentration and exposure time are chosen individually.', bullets: ['Glow & a smoother skin surface', 'Refined pores, an even complexion', 'Helps with impurities & mild pigmentation'] },
    indications: { title: 'Indications', items: ['Dull complexion, roughness', 'Enlarged pores, impurities', 'Fine lines, early sun damage', 'Mild pigmentation/post-acne marks'] },
    contra: { title: 'Contraindications', items: ['Active inflammation/infection, open lesions', 'Acute herpes, severe rosacea/eczema flare-ups', 'Pregnancy/breastfeeding (only very gentle peels)', 'Retinoid therapy (consultation required)'], note: 'Acid type & strength are determined individually on site.' },
    steps: [['Questions & skin analysis', 'Skin condition, goals & choice of peel.'], ['Preparation', 'Cleansing & degreasing; protection of sensitive areas.'], ['Peel & neutralisation', 'Application with precise timing.'], ['Finish & care', 'Soothing care, SPF advice, course planning.']],
    results: { title: 'Results & Longevity', items: ['Glow & refined pores after a few days', 'A more even complexion over 2–6 weeks', 'Course of 3–6 sessions (depending on peel strength)'], note: '*Brief redness possible; use SPF 50 consistently.', stats: [['30–45', 'Minutes'], ['3–6', 'Sessions (course)'], ['2–4', 'Weeks apart']] },
    prices: [
      { name: 'PRX-T33 Peel', desc: 'A biorevitalising peel without peeling – for a fresh, radiant complexion.' },
    ],
    faq: [
      ['Is there downtime?', 'Usually not. Brief redness or slight tingling is possible; depending on strength, fine flaking may occur in the following days.'],
      ['What should I consider after the peel?', 'No intense exercise, sauna or solarium for 24–48 hours. Use high SPF daily and gentle care; pause retinoids and strong acids initially.'],
      ['Who is the course suitable for?', 'For dull complexions, large pores, impurities or mild pigmentation. With active acne or rosacea we choose gentler protocols.'],
    ],
  },
};

export const EN_TEAM = [
  {
    role: 'Specialist in Radiology · Aesthetic Medicine',
    roleShort: 'Physician for Aesthetic Medicine',
    alt: 'Dr. med. Roya Jeyrani – physician for aesthetic medicine in Zurich',
    bio: [
      'After studying medicine in Hamburg (2001), Roya began her specialist training in radiology in Essen. In 2005 she continued her training at the Inselspital in Bern, obtained her specialist title in radiology in 2007 and her doctorate the following year.',
      'She discovered her passion in aesthetic medicine. She has completed numerous courses and has worked in medical aesthetics for many years. Regular further training helps her to always offer patients the very best.',
      'In 2018 she attended advanced training in Seoul to learn the latest methods and trends in lifting with absorbable threads.',
    ],
    facts: ['Medical studies in Hamburg', 'Specialist title in radiology (Inselspital Bern)', 'Thread lift training, Seoul 2018'],
  },
  {
    role: 'Medical-Cosmetic Therapist · Laser Safety Officer',
    roleShort: 'Medical-Cosmetic Therapist',
    alt: 'Agnieszka Jaggy – medical-cosmetic therapist at Perfect Shape Zurich',
    bio: [
      'Naturopath (in training) and medical-cosmetic therapist with further training in device-based cosmetics (cavitation, shockwave therapy, RF microneedling, HIFU ultrasound, cryolipolysis).',
      'Graduate sports scientist with courses in sports medicine (lymphatic drainage, back training) and nutritionist specialising in cellulite. Certified laser safety officer for working with diode lasers.',
    ],
    facts: ['Certified laser safety officer', 'Graduate sports scientist', 'Nutritionist (cellulite specialist)'],
  },
];

export const EN_REVIEW_TAGS = ['Lip enhancement with hyaluronic acid', 'Regular client for over 3 years'];

export const EN_HOME_FAQ = [
  ['Where is Perfect Shape Zurich located?', 'Our studio is at Bahnhofstrasse 94 (2nd floor), 8001 Zurich – just a few minutes’ walk from Zurich main station (Hauptbahnhof) and easy to reach by tram, train or on foot.'],
  ['How can I book an appointment?', 'Fastest online – 24/7 via our booking system. You can also reach us by phone at +41 76 608 61 61, via WhatsApp or by email.'],
  ['Who performs the treatments?', 'Diagnosis and treatments are performed by certified physicians and qualified specialists – including Dr. med. Roya Jeyrani and Agnieszka Jaggy, a certified laser safety officer.'],
  ['What does a treatment cost?', 'Our prices page shows transparent guide prices for all treatments – e.g. laser hair removal from CHF 40, lip enhancement from CHF 160 or thread lifts from CHF 240. The final cost is confirmed after your individual consultation.'],
  ['Can I reschedule or cancel an appointment?', 'Yes, free of charge up to 24 hours before your appointment. For late cancellations or no-shows we charge a fee of CHF 50.'],
  ['How can I pay?', 'Payment is made directly after the treatment in cash, by card or with TWINT.'],
];
